### ISSUE TITLE
Implement remote mailbox

### ISSUE THREAD

**Issue by VesaKarvonen** [Hopac/Hopac#10]
Public Hopac libs do not directly provide primitives for distributed computing.  Implement a "remote" mailbox for communication between nodes on (potentially) separate physical nodes.  Provide mechanisms to easily connect nodes, create remote mailboxes and observe node failures (Erlang monitor_node -> Node.Alt.down node).

**Comment by vasily-kirichenko** [comment]
To have remote mailboxes would be awesome.

**Comment by VesaKarvonen** [comment]
Contributions are welcome! :)

I'm currently not working on any project where such a thing would be needed.  If someone is interesting in working on a remote mailbox, I would be happy to help with the design.

**Comment by VesaKarvonen** [comment]
It should be possible and might be an interesting exercise to wrap ZeroMQ so that one could use ZeroMQ sockets with Hopac.  A receive operation from a socket could probably be exposed as an alternative and a send operation could be a job.  A poll loop (or possibly multiple poll loops) would be run in background threads hidden from the user.  As many ZeroMQ operations are blocking, they must not be performed directly in Hopac jobs, because blocking prevents the Hopac worker thread from being used to run other Hopac jobs.  While this organization would be less performant than direct use of ZeroMQ, it would, from the users point of view, decouple ZeroMQ sockets from particular native threads and allow them to be used conveniently from any number of lightweight concurrent jobs.
