### ISSUE TITLE
Src.value raises "Src closed" error when running with high throughput 

### ISSUE THREAD

**Issue by scifral** [Hopac/Hopac#101]
I'm hitting this error frequently when writing 10-100K values to a Stream Src in a tight loop.
I modified the isFull check within the Src.value operation to only throw if the filled value is Nil.
Is that a valid fix?

**Comment by polytypic** [comment]
Thanks for reporting the issue!  The old implementation was clearly broken and only worked when events were produced from a single job.  The new implementation makes all ops on stream sources atomic.  I'll look into making a new release later today.
