### ISSUE TITLE
Randomly consume messages from dynamic set of mailboxes

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#104]
So I need to consume message in random fashion from a dynamic set of `Mailbox`es:
```fsharp
let worker name addMb removeMb =
    Job.iterateServer [] (fun (mbs: Mailbox<int> list) ->
        (Alt.chooser mbs ^=> fun msg ->
             Console.WriteLine (sprintf "%s\t%A" name msg)
             timeOutMillis 500 >>-. mbs)
        <|>
        addMb ^-> fun mb -> mb :: mbs
        <|>
        removeMb ^-> fun mb -> mbs |> List.partition ((=) mb) |> snd)
    |> start

let addMb = Ch()
let removeMb = Ch()

worker "*" addMb removeMb
worker "**" addMb removeMb
worker "***" addMb removeMb

let mb1 = Mailbox<int>()
let mb2 = Mailbox<int>()

addMb *<- mb1 |> run
addMb *<- mb2 |> run

removeMb *<- mb1 |> run
removeMb *<- mb2 |> run

for _i in 1..1000 do mb1 *<<+ 1 |> run
mb2 *<<+ 2 |> run
```
It seems to work OK. Is the code looks good for you? I'm worried about the situation when there are a lot of messages in any (or all) of `mbs` mailboxes and we add another mailbox (`addMb *<- mb`), then the mailbox won't be added until there is no messages in already added mailboxes (since worker will always synchronize on `Alt.chooser ...` because it's the first alternative worker synchronized on.

**Comment by polytypic** [comment]
It looks basically ok to me.  It would be good to know more about the expected distribution of operations.  Using mailboxes is always a bit suspect because of the unbounded buffering.

Would it be better to have the alternatives in the order `removeMb`, `addMb` and `mbs`?

You could also choose randomly between all the alternatives:

```fs
let worker name addMb removeMb =
    let mbs = HashSet<_> ()
    mbs
    |> Seq.map ^ Alt.afterJob ^ fun msg ->
         sprintf "%s\t%A" name msg |> Console.WriteLine
         timeOutMillis 500
    |> Seq.append [|addMb    ^-> (mbs.Add    >> ignore)
                    removeMb ^-> (mbs.Remove >> ignore)|]
    |> Alt.chooser
    |> Job.forever
    |> start
```

**Comment by polytypic** [comment]
BTW, note that in

```fs
        addMb ^-> fun mb -> mb :: mbs
        <|>
        removeMb ^-> fun mb -> mbs |> List.partition ((=) mb) |> snd)
```

`addMb` and `removeMb` are asymmetric in the sense that `addMb` always adds a mb even if there are duplicates while `removeMb` removes all duplicates.

**Comment by vasily-kirichenko** [comment]
Thanks, actually the problem drifted to a slightly different direction:
```fsharp
type Task = { Id: int }

let create () =
    let addTaskCh = Ch<Task>()
    let getTaskCh = Ch<Task>()

    Job.iterateServer (Map.empty, []) (fun (mbsByTaskId: Map<int, Mailbox<Task>>, mbs: Mailbox<Task> list) ->
        (addTaskCh ^=> fun (task: Task) ->
            printfn "Adding task. Mailboxes: %A" mbs
            match mbsByTaskId |> Map.tryFind task.Id with
            | Some mb -> mb *<<+ task >>-. (mbsByTaskId, mbs)
            | None ->
                let mb = Mailbox()
                mb *<<+ task >>-. (mbsByTaskId |> Map.add task.Id mb, mb :: mbs)
        )
        <|>
        Alt.chooser mbs ^=> fun task -> getTaskCh *<- task >>-. (mbsByTaskId, mbs)
    )
    |> start

    addTaskCh, getTaskCh

let addCh, getCh = create()

let consumer name =
    Job.foreverServer (getCh ^=> fun task ->
        job {
            printfn "[%s] Got %A. Timeout..." name task
            do! timeOutMillis 5000 
            printfn "[%s] free." name
        })
    |> start

consumer "C1"
consumer "C2"

for taskId in 1..2 do
    for _i in 1..5 do addCh *<+ { Id = taskId } |> run
```
output:
```
Adding task. Mailbox count: 0
Adding task. Mailbox count: 1
Adding task. Mailbox count: 1
Adding task. Mailbox count: 1
Adding task. Mailbox count: 1
Adding task. Mailbox count: 1
Adding task. Mailbox count: 2
Adding task. Mailbox count: 2
Adding task. Mailbox count: 2
Adding task. Mailbox count: 2
[10-Jun-16 13:09:08, C2] Got {Id = 1;}. Timeout...
[10-Jun-16 13:09:08, C1] Got {Id = 2;}. Timeout...
[10-Jun-16 13:09:13, C2] free.
[10-Jun-16 13:09:13, C2] Got {Id = 2;}. Timeout...
[10-Jun-16 13:09:13, C1] free.
[10-Jun-16 13:09:13, C1] Got {Id = 1;}. Timeout...
[10-Jun-16 13:09:18, C1] free.
[10-Jun-16 13:09:18, C2] free.
[10-Jun-16 13:09:18, C1] Got {Id = 2;}. Timeout...
[10-Jun-16 13:09:18, C2] Got {Id = 2;}. Timeout...
[10-Jun-16 13:09:23, C2] free.
[10-Jun-16 13:09:23, C1] free.
[10-Jun-16 13:09:23, C2] Got {Id = 2;}. Timeout...
[10-Jun-16 13:09:23, C1] Got {Id = 1;}. Timeout...
[10-Jun-16 13:09:28, C1] free.
[10-Jun-16 13:09:28, C2] free.
[10-Jun-16 13:09:28, C1] Got {Id = 1;}. Timeout...
[10-Jun-16 13:09:28, C2] Got {Id = 1;}. Timeout...
[10-Jun-16 13:09:33, C1] free.
[10-Jun-16 13:09:33, C2] free.
```
The whole thing should behave exactly as `Mailbox`, but keep a `Mailbox` for each `taskId` internally:
```
                           |-> mb (taskid =  1) *****************    |
msg(taskid = 1) -> addCh ->|-- mb (taskid =  2)            ******    |-> getCh -> msg
                           |-- mb (taskid = 10)        ********** -> |
```
It seems to work OK, but I'm a bit worried if `send`ing messages to `addCh` is a good thing. If I used `give`, then adding messages would block, which is not what I want.

**Comment by polytypic** [comment]
Hmm... What is the end result you are trying to achieve?  It seems like you are trying to make a task queue from which you can get tasks with equal probability to get a task of a particular id.  So, if you happen to have tasks with ids a, b, and c, then no matter how many of each id you have, you will get a, b, or c with a probability of 1/3.  Is this the idea?

**Comment by vasily-kirichenko** [comment]
Yes, absolutely. No matter how much tasks of each id there are in mailboxes, they should be consumed evenly.

**Comment by vasily-kirichenko** [comment]
BTW, I was thinking what a solution would be if I wanted to get tasks from mailboxes with largest number of messages first. Since `Mailbox` is opaque about it's length, we would have to keep a separate counter on our own. Something like this:
```fsharp
type SizedMb<'a> =
  { Mb: Mailbox<'a>
    Size: int }

(mbs |> List.sortBy (fun smb -> -smb.Size) |> Alt.choose) ^=> ...
```
Firstly, it looks a bit inefficient (sorting and creating a new `list` every time). Secondly, it does not do what I wanted: `Alt.choose` will get messages from _the queue with largest number of messages_ until it's length reaches (2nd-most-filled-queue.lenght - 1), then it starts to get messages from that 2nd mailbox and so on. 

I think it would be great to provide a way to define user's own strategy for `Alt.choose`, so `Alt.chooser` could be expressed as `Alt.choose (fun (as: Alt<_> seq) -> ...`. The problem is that `Alt.choose` operates on abstract `Alt<_>`s, which does not carry any data (like mailbox's length) that can be used for implementing the strategy function.

**Comment by polytypic** [comment]
Sorry, I haven't had time to look into this more carefully.  Just a quickish note.  Rather than using mailboxes and choose to create a probability distribution, you could just collect the tasks (messages) into an ordinary sequential data structure from which you can obtain a task with the desired probability distribution and make the server offer only two alternatives: one for adding a task and other for taking a task.  Here is a kind of generic solution (untested code):

```fs
type Bag<'x> (selectRandom: uint64 -> seq<'x> -> int) =
  let addCh = Ch ()
  let takeCh = Ch ()
  do let elems = ResizeArray<_> ()
     addCh ^-> elems.Add <~> Alt.random ^ fun random ->
         if 0 = elems.Count then
           Alt.never ()
         else
           let i = selectRandom random elems
           takeCh *<- elems.[i] ^-> fun () ->
           let iLast = elems.Count-1
           elems.[i] <- elems.[iLast]
           elems.RemoveAt iLast
     |> Job.forever
     |> server
  member this.Add (task) = addCh *<- task
  member this.Take = takeCh :> Alt<_>
```

In your case you will want to use a different data structure for storing the tasks so that you can make the random choice efficiently (in `O(1)` time).

**Comment by vasily-kirichenko** [comment]
Thanks. Actually I started initially with a similar code (I used `List<Queue>` as the data structure), but decided to switch to `Alt.chooser <Mailbox list>` as it much simpler and works well for my case.
