### ISSUE TITLE
Run a job on ThreadPool

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#105]
In this issue https://github.com/Hopac/Hopac/issues/26#issuecomment-63172608 I found a piece of code  that returns a job, which is executed on `ThreadPool`:
```fsharp
type ThreadPool with
    static member runAsJob (op: unit -> 'x) : Job<'x> =
        Job.Scheduler.get() >>= fun sr ->
        let rV = IVar()
        fun _ -> Scheduler.start sr (try rV *<= op () with e -> rV *<=! e)
        |> ThreadPool.QueueUserWorkItem
        |> ignore
        rV
```
(I've tested it and confirmed that it _is_ executed on `ThreadPool`, outside Hopac pool).

* Could you elaborate on how this works? It seems `Scheduler.start` is called from a `ThreadPool` thread, but does it guarantee that `op` is executed in that thread?
* How can I run a _job_ on `ThreadPool` (I mean not a `unit -> 'a` function, but a ready to execute `Job`)?

**Comment by polytypic** [comment]
What happens is that the function `fun _ -> Sche...` is queued to the `ThreadPool`.  That function then immediately runs `op ()`.  So, it is guaranteed that `op ()` runs on a `ThreadPool` thread.

You can't quite run jobs on `ThreadPool` threads.  You could use `QueueUserWorkItem` to queue a call to `start (myJob : Job<_>)`.  However, this will only start running the job on the `ThreadPool` thread&mdash;much like `Async.StartImmediate`.  If the job blocks (waits for a message) or performs enough operations, it will be transferred to a Hopac worker thread.

**Comment by vasily-kirichenko** [comment]
Thanks!
