### ISSUE TITLE
Deadlocking interop

### ISSUE THREAD

**Issue by haf** [Hopac/Hopac#110]
Greetings. As it happens, I'm wrapping the WinRM API. Unfortunately I've run into a road-block.

The API has 1) `Begin-/End-Invoke`, 2) `(ps : PowerShell).Streams.Error.{DataAdding,Completed}`. I'm trying to join the EndInvoke with the Completed event of the Error stream, but for some number of runs; about half of them; everything freezes up.

I have code like this:

``` fsharp
// suspicious function 
    let streamOf n (psdc : PSDataCollection<_>) =
      let mb = Mailbox ()
      let stop = IVar ()
      psdc.DataAdding.Add <| fun args ->
        printDataAdding n args
        mb *<<+ args |> start
      psdc.Completed.Add <| fun args ->
        printCompleted n args
        stop *<= () |> start
      Stream.indefinitely mb
      |> Stream.takeUntil stop

// a little later in the file:

      job {
        try
          let outputs = subscribeStreams ps returned

          let! res = Job.fromBeginEnd (beginInvoke ps) ps.EndInvoke

          if ps.HadErrors then
            printfn "PowerShell had errors; draining stream"
            let! errors =
              outputs.error
              |> Stream.foldFromBack (Job.result [])
                                     (fun s t -> s |> Job.map (fun s -> t :: s))
            do! rI *<= Choice.createSnd errors

          else
            printfn "PowerShell succeeded; draining stream"
            let objects =
              Seq.foldBack (fun t s -> t :: s) res []

            do! rI *<= Choice.create objects
        with e ->
          //printfn "in job, writing transport exception"
          do! rI *<=! e
        }

// tested with
node
|> WindowsNode.runCommand ("Write-Error", ["We know, we know"])
|> run

// trace output
WindowsNode: (cb) availability: Busy
PowerShell: E.DataAdding(
  PowerShellInstanceId=9c113bd1-34dc-48e3-9b0a-648deecab88f,
  ItemAdded=We know, we know
)
WindowsNode: (cb) availability: Available
PowerShell had errors; draining stream
// nothing happens here
```

In short, the draining of the stream depends on

```
psdc.Completed.Add <| fun args ->
  printCompleted n args
  stop *<= () |> start
```

Firing before the job scheduler blocks on the Stream fold; otherwise the stream is never terminated and cannot be folded. However, despite only having a single `run`, at the topmost level (albeit with desktop GC), it would seem that is never fired.

It can be circumvented by passing a `p: Promise<unit>` to make it `Stream.takeUntil (stop <|> p)` and then giving the promise a unit value after `EndInvoke` has returned; but then in about half of the cases, the output is never fully captured.

Is this a scheduler issue?

**Comment by vasily-kirichenko** [comment]
`start` in the suspicious function looks suspicious :) Try to use `queue`. Just speculating :)

**Comment by haf** [comment]
I can't because `queue` it doesn't guarantee order, according to @polytypic

**Comment by vasily-kirichenko** [comment]
Does it work if you use queue instead of top level run?

**Comment by haf** [comment]
I'm afraid that it didn't change anything.

**Comment by polytypic** [comment]
Haven't read the code further yet, but when written like this

```fs
// suspicious function 
    let streamOf n (psdc : PSDataCollection<_>) =
      let mb = Mailbox ()
      let stop = IVar ()
      psdc.DataAdding.Add <| fun args ->
        printDataAdding n args
        mb *<<+ args |> start
      psdc.Completed.Add <| fun args ->
        printCompleted n args
        stop *<= () |> start
      Stream.indefinitely mb
      |> Stream.takeUntil stop
```

there is no guarantee that all the args put into the mailbox can (and by extension will) be consumed by the stream reader, because the stream ends after the stop var is written whether or not all the messages are taken from the mailbox.

Assuming you want all the args to be readable from the stream, an easy way to implement it is to use a [stream source](http://hopac.github.io/Hopac/Hopac.html#def:module%20Hopac.Stream.Src):

```fs
  let streamOf n (psdc : PSDataCollection<_>) =
    let src = Stream.Src.create ()
    psdc.DataAdding.Add <| fun args ->
      printDataAdding n args
      Stream.Src.value src args |> start
    psdc.Completed.Add <| fun args ->
      printCompleted n args
      Stream.Src.close src |> start
    Stream.Src.tap src
```

**Comment by haf** [comment]
@polytypic That makes sense. Will try today! Thank you!

**Comment by haf-raysearchlabs** [comment]
Unfortunately that didn't work; the job still blocks on the `Stream.foldFromBack`.

**Comment by vasily-kirichenko** [comment]
In such situations I add a lot of `printfn` statements all over the code and see what's going on.

**Comment by haf-raysearchlabs** [comment]
Yes, so am I doing; this is what the trace looks like:

```
> stderr();;
val it : unit = ()
> WindowsNode: (cb) availability: Busy
PowerShell: E.DataAdding(
  PowerShellInstanceId=285cf431-c284-45ad-9129-8f6339ed51eb,
  ItemAdded=We know, we know
)
WindowsNode: (cb) availability: Available
(job) PowerShell had errors; draining stream // after sync check of ps.HadError
(job) Wrote rI
(stream) System.Management.Automation.DataAddingEventArgs
PowerShell: E.Completed: ()
(cb) Completed
(stream) Completed
WindowsNode: available.
```

With

```
          if ps.HadErrors then
            printfn "(job) PowerShell had errors; draining stream"
            outputs.error
            |> Stream.onCloseFun (fun () -> printfn "(stream) Completed")
            |> Stream.iterFun (fun x -> printfn "(stream) %A" x)
            |> queue
            do! rI *<= Choice.createSnd []
            printfn "(job) Wrote rI"
          else
            printfn "PowerShell succeeded; returning PSObject-s"
            let objects =
              Seq.foldBack (fun t s -> t :: s) res []

            do! rI *<= Choice.create objects
```

If I replace the queue with the previous fold, it goes back - the stream callback that a value has been added is run, but the close event on the stream happens at some point after running the job, but binding inside the job, on a job that is dependent on the stream closing, seems to prohibit the callback from WinRM.

**Comment by polytypic** [comment]
It is difficult to tell from the given snippets.  Could this be due to `Stream.foldFromBack` being lazy (and `Stream.iterFun` being eager)?

**Comment by polytypic** [comment]
When is `Complete` called on the `PSDataCollection`?  Is the call only made after `rI` var is filled?

**Comment by haf-raysearchlabs** [comment]
Yes, maybe due to eagerness; but fold is a structure destroying operation that's by definition eager; right? It will try to consume the whole stream if I block on it?

If I queue only the iterFun, then:

```
> stderr();;
val it : unit = ()
> WindowsNode: (cb) availability: Busy
PowerShell: E.DataAdding(
  PowerShellInstanceId=f4e2139b-ee95-4c2c-8393-cd3ba73c035a,
  ItemAdded=We know, we know
)
WindowsNode: (cb) availability: Available
(job) PowerShell had errors; draining stream, thread id 27
(job) Wrote rI, thread id 27
PowerShell: E.Completed: ()
(cb) Completed, thread id 27
(stream) System.Management.Automation.DataAddingEventArgs, thread id 38
(stream) Completed, thread id 38
WindowsNode: available.
```

Where `cb` is the callback from WinRM, `stream` is logging inside `iterFun` and `job` is in the job monad. If I instead use fold then the job blocks; perhaps as you say because there's nothing pulling on the stream, so it never completes... However, the Completed event then never fires either; so that would seem to imply that the wait that Hopac creates interferes with the thread that would fire the WinRM event. In fact; I would like to keep the WinRM thread on its own thread; as opposed to a worker thread from Hopac, because then I would be able to ensure that threads don't get stuck when they need to run, from outside of Hopac's cooperative model.

**Comment by polytypic** [comment]
Hmm... Does `dispose` actually trigger the `Completed` events?  If so, then there is a cyclic dependency that needs to be broken (dispose is called after stream ends, but stream only ends after dispose is called).

**Comment by haf-raysearchlabs** [comment]
Wow, my man. Well spotted. Resolving that cycle made it work. I wonder why the error stream doesn't close until Dispose is called; presumably the error output would be contained in time for a given invocation in PS...

**Comment by polytypic** [comment]
> fold is a structure destroying operation that's by definition eager; right?
> It will try to consume the whole stream if I block on it?

The `foldBack` and `foldFromBack` stream combinators are lazy and, depending on the given combiner function, they do not necessarily consume the whole stream.  For example, you could write a function to extract the head of a stream like this:

```fs
let head xs =
  xs
  |> Stream.foldFromBack (Job.raises (Exception "Empty")) (fun _ x ->
       Job.result x)
```

The above stream combinator, `head`, only examines at most the first `Cons` of the given stream `xs`.

In this case,

```fs
            let! errors =
              outputs.error
              |> Stream.foldFromBack (Job.result [])
                                     (fun s t -> s |> Job.map (fun s -> t :: s))
```

the computation proceeds in such a way that the entire stream is first deconstructed and a sequence of `Job.map` operations is built and finally the sequence of operations is executed.  It would likely be faster to use an ordinary fold and list reversal.

However, in retrospect, the laziness of `foldFromBack` could not possibly have been a cause of the problem in this case.
