### ISSUE TITLE
Hopac v0.3 - v0.3.3 has wrong dependency declaration on NuGet

### ISSUE THREAD

**Issue by haf** [Hopac/Hopac#111]
Getting some errors after testing to upgrade to Hopac 0.3 on Windows:

https://ci.appveyor.com/project/GrantCrofton/http-fs/build/1.5.1.163#L3423

All works fine on mono:

https://travis-ci.org/relentless/Http.fs/jobs/148359897

For Logary I also get an exception, probably due to an old Http.fs version.

https://travis-ci.org/logary/logary/jobs/148357886#L1258

**Comment by polytypic** [comment]
Not currently at my laptop, but I noticed this in the logary output:

System.TypeLoadException: Could not load type 'Hopac.Core.AwaitTask' from assembly 'Hopac.Core, Version=0.0.0.36, Culture=neutral, PublicKeyToken=null'.

Note the version number.

**Comment by haf** [comment]
Yes, I saw that too in Logary, which is why I'm upgrading Http.fs. https://ci.appveyor.com/project/GrantCrofton/http-fs/build/1.5.1.164 – here's something funky going on with Hopac in that project.

**Comment by haf** [comment]
I pushed Http.fs w/ 0.3 in the meanwhile to see if I can get Logary working on linux. Currently building https://travis-ci.org/logary/logary/builds/148366517

**Comment by haf** [comment]
Hopac v0.3.0-v0.3.3 should be unpublished because of broken dependencies for F# core.

**Comment by polytypic** [comment]
Unpublished those versions.
