### ISSUE TITLE
Promise returning `unit` through c'tor is dangerous

### ISSUE THREAD

**Issue by haf** [Hopac/Hopac#113]
<img width="725" alt="screen shot 2016-08-11 at 17 19 38" src="https://cloud.githubusercontent.com/assets/193115/17593976/f2b4b8de-5fe7-11e6-8be8-43c3d1f2e8d6.png">

What it looks like in Logary above. After careful inspection, we're returning `Promise.Now.withValue ()` but [this is how people](https://github.com/logibit/Fakta/compare/ce4578b506...e74d36b9fd#diff-7dc953b4c058dae0e331ddff0d65de5eR17) who are not me or you think by default.

So I think we should upgrade the new API with the c'tor of Promise to a bug – a bug in how you're intended to use the API versus what people actually do. Also see https://github.com/Hopac/Hopac/commit/5a60797462deff83135fa0ee02403671045774ff#commitcomment-18537736

**Comment by polytypic** [comment]
It does seem like the overloads can be error prone.

**Comment by polytypic** [comment]
Here are roughly the types of functions I'd like to have:

```fsharp
never<'x> :                         Promise<'x>
value:                  'x   ->     Promise<'x>
error:                  exn  ->     Promise<'x>

memo:               Job<'x>  ->     Promise<'x>
memoFun:  (unit ->      'x)  ->     Promise<'x>
memoJob:  (unit -> #Job<'x>) ->     Promise<'x>

queue:              Job<'x>  -> Job<Promise<'x>>
queueFun: (unit ->      'x)  -> Job<Promise<'x>>
queueJob: (unit -> #Job<'x>) -> Job<Promise<'x>>

start:              Job<'x>  -> Job<Promise<'x>>
startFun: (unit ->      'x)  -> Job<Promise<'x>>
startJob: (unit -> #Job<'x>) -> Job<Promise<'x>>
```

**Comment by neoeinstein** [comment]
Also `unit<'x> : Promise<unit>`.

**Comment by haf** [comment]
Isn't `Job.result` as much a value as `Promise.value`?

**Comment by polytypic** [comment]
@haf With a breaking change it could be made so that we would have only

```
never<'x> : Promise<'x>
unit: Promise<unit>
result: 'x -> Promise<'x>
raises: exn -> Promise<'x>
```

and those would also work as `Alt<_>`s and as `Job<_>`s.  For micro performance reasons the `Promise<_>` class would need to be changed though.

**Comment by haf** [comment]
Well, even though it hurts like hell every time you make a breaking change to Hopac, if you do it now before v1 then we can live happily ever after v1.

**Comment by polytypic** [comment]
[Related](https://github.com/Hopac/Hopac/pull/85)

**Comment by haf** [comment]
Ping

**Comment by polytypic** [comment]
Sorry, a bit too busy with other projects ATM.  Note that you can achieve the above interfaces outside of Hopac.  Proper implementation needs to be done at lower level to avoid performance degradation.

**Comment by haf** [comment]
That's alright. Just checking in :). Can't we just revert the commit (or pieces thereof) that removed support for Promise.create?

**Comment by polytypic** [comment]
You mean to de-obsolete [these](https://github.com/Hopac/Hopac/blob/master/Libs/Hopac/Hopac.fsi#L1474-L1492)?  IMO, they are to be removed eventually, but I agree that the overloaded constructors are too error prone, as discussed here, and I can't make the full changes to make promises work optimally as  replacements for `unit` and `result` right now.  If you like you can remove the obsolete markers and make a release?

**Comment by haf** [comment]
Yes, that sounds like a plan.

**Comment by haf** [comment]
"Fixed" with https://github.com/Hopac/Hopac/commit/443149d300c302e3ee4b85853e3e5911c2b1f008 – @polytypic Do you want me to leave the issue open?

**Comment by polytypic** [comment]
Yes, let's leave this issue open for now.
