### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by alexknips** [Hopac/Hopac#114]
Are there any plans of a .net Core version of this library? 
That would be awesome.

**Comment by polytypic** [comment]
I haven't yet put any effort into it, but I'm certainly not against a .NET Core port.

**Comment by haf** [comment]
See #118 – review and finalisation much appreciated if @alexknips you could assist with.

**Comment by polytypic** [comment]
Hopac nupkg with preliminary .NET Core support is now available.
