### ISSUE TITLE
Exception "forwarded" when calling Hopac from Http.fs

### ISSUE THREAD

**Issue by object** [Hopac/Hopac#115]
I often (but not always) get an exception from a multipart posts when the request fails with a single word "forwarded" as the error message. The call is made using Http.fs that uses Hopac internally (I used the version 0.3.10). I checked Hopac code and the only place that raises an exception with such error string is "forward" function which unconditionally throws an error:

let forward (e: exn) : 'x =
raise (exn ("forwarded", e))

Http.fs library doesn't use "forward" function so the call must be made from inside Hopac.

**Comment by polytypic** [comment]
Comment [here](https://github.com/relentless/Http.fs/issues/103#issuecomment-241358572).

**Comment by haf** [comment]
Seems fixed/no repro, see link.
