### ISSUE TITLE
Job to Alt?

### ISSUE THREAD

**Issue by slav** [Hopac/Hopac#117]
Hello. I have code similar to the one below.

```
    let rec procServerLoop registered started =
        getCancellationCh *<- cancellationIvar <|>
        (procCmdCh ^=> function
            | RegisterProcess proc -> procServerLoop (proc :: registered) started
            | StartRegistered ->
                procServerLoop [] (started @ (registered |> List.rev |> (List.map startProcess)))
            | Stop ->
                cancellationIvar *<= () ... ??? Now what?)
```

The intention here is to have a server which manages processes. Each process is passed an IVar to listen on. When IVar becomes "signaled", it indicates all processes need to stop.

Reading from IVar is an Alt (so easy to wait for it or do something else). However, in this case signalling IVar is a job. I need an alt. I could do

```
cancellationIvar *<= () |> start
Alt.unit()
```

But it doesn't feel right. Is this the recommended approach? Or is there a way to convert a job into an alt in this case?

**Comment by polytypic** [comment]
Assuming I understood what you are trying to achieve, then this is due to the typing of the [`^=>`](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Infixes.^=>) operator:

```fs
val ( ^=> ): Alt<'x> -> ('x -> #Job<'y>) -> Alt<'y>
```

This is a workaround for lack of subtyping used in many F# libraries and is discussed in [issue 30](https://github.com/Hopac/Hopac/issues/30).  What you strictly need to return from the function on the right hand side of `^=>` is a `Job<_>`, but any subtype will do.

In this case one way to appease the type checker is to write it like this:

```fs
  let rec procServerLoop registered started =
      getCancellationCh *<- cancellationIvar <|>
      procCmdCh ^=> function
         | Stop ->
           cancellationIvar *<= ()
         | RegisterProcess proc ->
           upcast procServerLoop (proc :: registered) started
         | StartRegistered ->
           upcast procServerLoop [] (started @ (registered |> List.rev |> List.map startProcess))
```

Another way would be to use e.g. [`asJob`](http://hopac.github.io/Hopac/Hopac.html#dec:val%20Hopac.Hopac.asJob) or `:> Job<_>` ascription instead of `upcast`.

**Comment by slav** [comment]
Thank you. This helped.

**Comment by slav** [comment]
Actually, my biggest error was forgetting to pass loop function through Job.delay. Doing that fixed several issues, including the need to upcast.

**Comment by polytypic** [comment]
So, I guess the snippet didn't include all of the function?

The original snippet should not require `Job.delay`.  Roughly all of the Hopac functions that return jobs (or alts or promises or ...) are essentially pure and the returned job needs to be explicitly run (in a way or another) to have an effect.  As the loop in the snippet only calls Hopac operations and does not perform an immediate recursive call it has no effect and should not require a `Job.delay`.

**Comment by slav** [comment]
The snipped only omitted launching loop and actually had several bugs. Here's the final snippet:

```
    let rec procServerLoop registered started = Job.delay <| fun () ->
        getCancellationCh *<- cancellationIvar ^=> (fun () -> procServerLoop registered started)
        <|>
        (procCmdCh ^=> function
            | Stop ->
                cancellationIvar *<= ()
            | RegisterProcess proc -> procServerLoop (proc :: registered) started
            | StartRegistered ->
                procServerLoop [] (started @ (registered |> List.rev |> (List.map startProcess))))

    procServerLoop [] [] |> Job.start >>-. { ProcessCmd = procCmdCh; GetCancellation = getCancellationCh }
```

And yes, don't think Job.delay is required. It does fix the issue with casting though. Should I avoid it here and upcast?

Also, just to confirm, I'm unable to use ```Job.server``` because loop function has 2 arguments, not just 1?

**Comment by polytypic** [comment]
Consider the following function:

```fs
let rec neverReturns () = neverReturns ()
```

It has the following signature:

```fs
val neverReturns: unit -> 'a
```

A function that never returns normally also never needs to create a return value.  Therefore the return type can be any type.

The `Job.server` (and other `server` primitives) use this to detect when they are given jobs that never return normally.  Consider the signature of `Job.server`:

```
val server: Job<Void> -> Job<unit>
```

It takes a job whose result type is `Void`, which is a type that does not have public constructors.  In order for a job to have such a result type, the job cannot return normally.  Knowing that the given job never returns normally, the `server` primitives can avoid allocating a so called continuation when they start running the job.  Avoiding allocations is one of the most effective ways to improve performance on .Net.

(Of course, in .Net it is possible to use e.g.  `Unchecked.defaultof<Void>`, but then you know you are cheating.  If you use that to return when using the `server` primitives, you will likely get a null pointer exception.)

The signature of the previous is `procServerLoop` is of the form

```fs
val procServerLoop: _ -> _ -> Job<unit>
```

The result type is `unit`, which indicates that the function may return.  Therefore the `server` primitives cannot be used to start the job.

To be able to use `server` primitives, the loop needs to be changed to never return.  One way to do that is to use `abort`:

```fs
    let rec procServerLoop registered started = Job.delay <| fun () ->
        getCancellationCh *<- cancellationIvar ^=> (fun () -> procServerLoop registered started)
        <|>
        (procCmdCh ^=> function
            | Stop ->
                cancellationIvar *<= () >>= Job.abort
            | RegisterProcess proc -> procServerLoop (proc :: registered) started
            | StartRegistered ->
                procServerLoop [] (started @ (registered |> List.rev |> (List.map startProcess))))

    procServerLoop [] [] |> Job.server >>-. { ProcessCmd = procCmdCh; GetCancellation = getCancellationCh }
```

**Comment by polytypic** [comment]
As mentioned previously, one of the most effective ways to improve performance is to avoid allocations.  With a few exceptions, all of the functions in Hopac that return jobs (or alts or ...) allocate.  This also applies to `Job.delay`. So, when written without it

```fs
    let rec procServerLoop registered started =
        getCancellationCh *<- cancellationIvar ^=> fun () -> procServerLoop registered started
    <|> procCmdCh ^=> function
            | Stop ->
                cancellationIvar *<= () >>= Job.abort
            | RegisterProcess proc -> upcast procServerLoop (proc :: registered) started
            | StartRegistered ->
                upcast procServerLoop [] (started @ (registered |> List.rev |> List.map startProcess))

    procServerLoop [] [] |> Job.server >>-. { ProcessCmd = procCmdCh; GetCancellation = getCancellationCh }
```

the loop performs fewer allocations per iteration.  This is safe, because there are no immediate effects performed by the function and there are no immediate recursive calls.

It is possible to reduce allocations even further.  For example, the subexpression `getCancellationCh *<- cancellationIvar` could be moved outside the function.  When state is passed through function arguments, some allocations are difficult to avoid.  By changing the server to use mutable state, even more allocations can be eliminated:

```fs
    let registered = ResizeArray ()
    let started = ResizeArray ()

    let procServerLoop =
        getCancellationCh *<- cancellationIvar
    <|> procCmdCh ^-> function
            | Stop ->
              IVar.TryFill cancellationIvar () |> start
            | RegisterProcess proc ->
              registered.Add proc
            | StartRegistered ->
              registered
              |> Seq.map startProcess
              |> started.AddRange
              registered.Clear ()

    procServerLoop |> Job.foreverServer >>-. { ProcessCmd = procCmdCh; GetCancellation = getCancellationCh }
```

The above differs from the previous loops in that the server loop is not terminated after `Stop`.  Assuming there are no reference left to the server then the end result is pretty much the same.

BTW, what does `startProcess` do?  Does it call some Hopac primitive (e.g. `Hopac.start` or `Hopac.queue`) to start jobs?  If so, then it would likely be more performance to use `Seq.mapJob` to iterate through the sequence and use `Job.start` or `Job.queue` to start the processes.

Note that I'm mentioning these in case they might be helpful (now or in the future).  If performance is good enough already, then there is little point in optimizing things.

**Comment by slav** [comment]
Thank you for taking the time to explain everything. Perhaps it'd be nice to add these details to the documentation?

The ```startProcess``` launches non-Hopac, self-contained long-running services on new threads. I left out parts related to managing them, below is the full code.

The main motivation behind this service was to have one place to manage all background services that are running in the application in one place. It uses cancellation token for services we already have that are not in Hopac domain and when needed I can also indicate to Hopac jobs that are doing some work which I want stopped (for example working with disks or network in the background) that program is shutting down.

There're not a lot of processes, so no need to do more of optimization. But I greatly appreciate your insights, as it helps understand Hopac and performance implications of things better.

```
type Process = { Name: string; FProc: CancellationToken -> unit }
type ProcessReq =
    | RegisterProcess of Process
    | StartRegistered // starts all registered processes
    | Stop // stops all started processes and exits

type ProcessServer = {
    ProcessCmd: Ch<ProcessReq>; // Command to register process or control processes
    GetCancellation: Ch<IVar<unit>> } // Return IVar which will become activated when there's a request for cancellation

let createProcessServer() = Job.delay <| fun() ->
    let procCmdCh = Ch<ProcessReq>()
    let getCancellationCh = Ch<IVar<unit>>()
    let cancellationTokenSource = new CancellationTokenSource()
    let cancellationIvar = IVar()

    let exponentialDelay failedAttemptsCount: TimeSpan =
        let attemptsCount = if failedAttemptsCount > 9 then 9 else failedAttemptsCount

        let delayInSeconds = (1.0 / 2.0) * ((2.0 ** double attemptsCount) - 1.0)
        TimeSpan.FromSeconds(delayInSeconds)

    let startProcess (proc: Process) =
        let procAction() =
            let log = Log.ForContext("processName", proc.Name)
            let token = cancellationTokenSource.Token
            let mutable failureCount = 0us
            while not token.IsCancellationRequested do
                let started = DateTime.UtcNow
                try
                    proc.FProc(token)
                    log.Information("Process terminated")
                    token.WaitHandle.WaitOne(60 * 1000) |> ignore // wait 1 min and try restart
                with
                    | x ->
                       let uptimeHours = Math.Round((DateTime.UtcNow - started).TotalHours, 1)

                       failureCount <- if uptimeHours > 12.0 then 0us else failureCount + 1us

                       let sleepDuration = exponentialDelay (int failureCount)
                       log.Error(x, "Failed after {hours} hours. Sleeping for {seconds} sec", uptimeHours, sleepDuration.TotalSeconds)
                       token.WaitHandle.WaitOne(sleepDuration) |> ignore

        Task.Factory.StartNew(procAction, TaskCreationOptions.LongRunning)

    let rec procServerLoop registered started =
        getCancellationCh *<- cancellationIvar ^=> (fun () -> procServerLoop registered started)
        <|>
        (procCmdCh ^=> function
            | Stop ->
                cancellationTokenSource.Cancel()
                cancellationIvar *<= () >>= Job.abort
            | RegisterProcess proc -> upcast procServerLoop (proc :: registered) started
            | StartRegistered ->
                upcast procServerLoop [] (started @ (registered |> List.rev |> (List.map startProcess))))

    procServerLoop [] [] |> Job.server >>-. { ProcessCmd = procCmdCh; GetCancellation = getCancellationCh }
```
