### ISSUE TITLE
Documentation: tooltips font is too small and unbalanced on high res displays on windows

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#121]
![image](https://cloud.githubusercontent.com/assets/873919/18100034/f2bafc9e-6ef1-11e6-908c-fb2dd2fbed55.png)

**Comment by polytypic** [comment]
Does it look better now?  I made some adjustments to the CSS earlier and I also just removed bold attribute from links in code samples so text will align better on some browsers (some browsers like Chrome and Firefox on OS X already managed to pull of alignment despite variable length bolded elements).  (One thing that is for sure is that the reference manual CSS is not mobile friendly.)

**Comment by neoeinstein** [comment]
Fonts now appear to be consistently sized to me.

**Comment by vasily-kirichenko** [comment]
Yes, it's fixed. Thanks!

![screenshot from 2016-09-28 21-58-59](https://cloud.githubusercontent.com/assets/873919/18927966/c7fba42c-85c6-11e6-9287-ecbca54417ed.png)
