### ISSUE TITLE
Fairness

### ISSUE THREAD

**Issue by haf** [Hopac/Hopac#126]
When running Logary samples I would like to generate some CPU load (this sample intends to plot CPU load).

Here's a trace:

```
V 2016-09-21T08:03:52.7928170+00:00: Will poll cpu every 0:00:00:00.8 [Logary.Registry.registry]
V 2016-09-21T08:03:52.8051530+00:00: Getting logger for metric cpu [Logary.Registry.registry]
D 2016-09-21T08:03:52.3826110+00:00: haf logged in [Logary.Samples.main]
  userName => "haf"
I 2016-09-21T08:03:52.3889980+00:00: adam logged in [Logary.Samples.main]
  userName => "adam"
V 2016-09-21T08:03:52.9150620+00:00: Composing 0 middlewares [Logary.Registry.registry]
ParJob: 102334155 - 29.502631s (0.000000 jobs/s)
D 2016-09-21T08:04:21.9062850+00:00: 0 [Processor.% Processor Time._Total]
D 2016-09-21T08:04:21.9066840+00:00: 0 [Processor.% User Time._Total]
D 2016-09-21T08:04:21.9067210+00:00: 0 [Processor.% Interrupt Time._Total]
D 2016-09-21T08:04:21.9067250+00:00: 0 [Processor.% Privileged Time._Total]
D 2016-09-21T08:04:22.7051090+00:00: 100 [Processor.% Processor Time._Total]
```

As you can see, for the 29 seconds it takes to run your (nicked with pleasure ;)) sample, nothing gets scheduled on the Logary side – this means that "too efficient, high load-" usage of Hopac in an app can halt other important parts of it.

```fsharp
module ParallelJob =
  open System.Diagnostics
  open Hopac.Infixes

  let mutable numSpawns = 0L

  let rec fib n = job {
    if n < 2L then
      return n
    else
      let! (x, y) = fib (n-2L) <*> fib (n-1L)
      return x + y
  }

  let run n =
    printfn "ParJob started"
    let timer = Stopwatch.StartNew ()
    let r = run (fib n)
    let d = timer.Elapsed
    printf "ParJob: "
    printf "%d - %fs (%f jobs/s)\n"
     r d.TotalSeconds (float numSpawns / d.TotalSeconds)
```

**Comment by polytypic** [comment]
Yes, that is how co-operative scheduling works.

One possible solution in your case might be to create a more co-operative way to generate CPU load.  Here is an idea:

```fs
  let rec blocker stop =
        stop
    <|> timeOutMillis 1 ^=> fun () ->
          Thread.Sleep blockMs // You should normally never do this!
          blocker stop
```

Start enough of those (pass the same `IVar` to them for stopping) and you can simulate load.

Currently `timeOutMillis 0` does not go through the timer priority queue.  It would be possible to add a combinator, e.g. with name `idle`, that would go through the timer priority queue with zero timeout.  This way the work would be picked up as soon as there is nothing else to do.

**Comment by haf** [comment]
Thanks. Makes sense.

**Comment by polytypic** [comment]
FYI, thanks to @neoeinstein, Hopac now has [`idle`](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Hopac.idle) combinator.
