### ISSUE TITLE
Local Scheduler with large number of worker threads

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#128]
The task is to run `processor.Process` in 100 parallel threads. `processor.Process` is non async, IO (network) bound method belonging to a third party API. 

``` fsharp
let threadCount = 100

let scheduler =
    Scheduler.create
        { Foreground = None
          IdleHandler = None
          MaxStackSize = None
          NumWorkers = Some threadCount
          TopLevelHandler = 
            Some ^ fun e -> job { Console.WriteLine e }}

using (new ObjectPool<_>((fun _ -> new KlDfs(settings)), capacity = 200u)) <| fun pool -> 
    File.ReadLines fileName
    |> Stream.ofSeq
    |> Stream.chooseFun parser
    |> Stream.afterEach (timeOut afterEachTimeout)
    |> Stream.mapPipelinedJob threadCount (fun (key, input) -> 
        job {
            let! res = 
                pool.WithInstanceJobChoice <| fun fs -> 
                    job { return processor.Process (key, input) fs }
            return key, res
        })
    |> Stream.foldFun (fun total (key, res) ->
          Interlocked.Increment count |> ignore
          if !count % 100 = 0 then printfn "..."
        )
    |> Scheduler.run scheduler
    |> ignore
```

It seems to work, but when I look at threads with dotTrace, it shows small number of worker thread (== logic processor count (16)):

![image](https://cloud.githubusercontent.com/assets/873919/18747837/16648096-80d8-11e6-99dc-977c28611c33.png)

**Comment by vasily-kirichenko** [comment]
One more question. This app seems to consume more and more memory as time goes. Is this pattern guarantees constant memory usage?
```fsharp
File.ReadLines <path to 50GB text file>
|> Stream.ofSeq
|> Stream.chooseFun parser
|> Stream.afterEach ...
|> Stream.mapPipelinedJob ...
|> Stream.foldFun ...
|> run
|> ignore
```

**Comment by polytypic** [comment]
The latter question lead to the discovery of a bug.  I assumed that C# would guarantee that when the lexical scope of variables ends then the variables would be considered garbage.  I've released a new version that fixes that bug.  Does the latest version fix the issue in your case?

What happens in the former question touches a pair of known issues in the scheduler implementation that are a part of why I want to remove the scheduler functionality.  The main issue that you ran into there is that not all operations maintain the scheduler.  When a job waiting for a message receives a message and the job is continued, in the current (broken) implementation, the job continues on the global scheduler or the scheduler of the other job involved in the communication.  The reason why this happens in your example is that the timer mechanism, when used through `timeOut`, is implicitly tied to the global scheduler.  (In the current implementation, the timer mechanism is a kind of "pluggable" component that needs to be attached to the "idle" mechanism of a scheduler.)

It would be possible to fix the scheduler mechanism so that when a job is started on a particular scheduler, it would stay on that scheduler, but I don't believe it is worth the trouble to fix it.  I'd rather drop scheduler support completely and simplify the implementation.

What I would recommend in your case is to use the ThreadPool (or perhaps some custom thread pool in case ThreadPool can't be configured to work well in this case) to run those blocking operations.

BTW, I think that it would be possible to reinstate support for running blocking code on the ThreadPool as jobs.  The reason why the support was removed was that ThreadPool is not available in many PCL profiles.  Currently Hopac only supports .NET Framework and .NET Core, which both provide ThreadPool.  Also, a ThreadPool is typically available on any platform that Hopac is worth porting to.  So, an interface to the ThreadPool could be provided by the Hopac.Platform library of the platform.

**Comment by vasily-kirichenko** [comment]
Thanks. About the memory leak, I'm afraid it's still there (comparing two dotMemory snapshots):

![image](https://cloud.githubusercontent.com/assets/873919/18778715/64baff3a-817e-11e6-99b0-ce4bbaf70f56.png)

**Comment by polytypic** [comment]
Hmm...

Can you provide a sample that reproduces the leak?

I haven't confirmed this, but one possibility might be that `run` would hold onto the stream.  Can you try changing `run` to `start`?

Also, if `run` is the culprit, then another immediate workaround would be to wrap it like this:

```fs
run << Job.delay <| fun () ->
File.ReadLines <path to 50GB text file>
|> Stream.ofSeq
|> Stream.chooseFun parser
|> Stream.afterEach ...
|> Stream.mapPipelinedJob ...
|> Stream.foldFun ...
```

Could you try with this alternative?

**Comment by polytypic** [comment]
I did a quick test and it seems that `run` indeed holds onto the job object (which in this case is a stream).  As an immediate workaround the alternative with `delay` should not leak, but I'll workaround the issue in `run`.  This also falls into what I would expect the language to handle already under [space safety](http://citeseer.ist.psu.edu/viewdoc/summary?doi=10.1.1.50.4500).  Basically the `run` function does not refer to the job object after starting it, so it should be eligible for GC.  Unfortunately, it seems, the F# + runtime does not consider the variable to be garbage.  Oh dear.

**Comment by vasily-kirichenko** [comment]
I must wait until the job is done, so I added an `IVar` and wait for it:
```fsharp
let finished = IVar()
    
File.ReadLines fileName
|> Stream.ofSeq
|> Stream.chooseFun parser
|> Stream.afterEach (timeOut afterEachTimeout)
|> Stream.mapPipelinedJob ...
|> Stream.foldFun ...
|> Job.bind (fun _ -> IVar.fill finished ())
|> start

run finished
```
It's still leaking.

**Comment by polytypic** [comment]
FYI, I made a new release with some potential fixes.

Now all the Streams benchmarks seem to run without leaks on .NET Core/Framework.  I tested this by replacing `Stream.iter` with a version that periodically shows `GC.GetTotalMemory true`.  Note that streams allocate heavily and this can make the runtime grow the heap aggressively to avoid spending time in GC.

One thing I found out is that it seems that Mono and .NET Core/Framework behave differently in terms of space safety: some programs (unexpectedly) leak under Mono, but do not leak (as expected) under .NET Core/Framework.  I have not investigated this in enough detail to find out the exact reason, but I suspect differences in tail call behavior.

**Comment by vasily-kirichenko** [comment]
I confirm the leak is gone 👍 Thanks a lot.

**Comment by polytypic** [comment]
@vasily-kirichenko FYI, I added a new `Job.onThreadPool` helper to run thunks on the `ThreadPool`.

**Comment by vasily-kirichenko** [comment]
It turns out I wrote such a function some time ago (or you wrote it, I cannot say) :) And even wrote a blog post about it :)) http://vaskir.blogspot.ru/2016/06/running-computational-intensive-code.html 

The function was as following:
```fsharp
type ThreadPool with
    static member runAsJob (op: unit -> 'x) : Job<'x> =
        Job.Scheduler.get() >>= fun sr ->
        let rV = IVar()
        fun _ -> Scheduler.start sr (try rV *<= op () with e -> rV *<=! e)
        |> ThreadPool.QueueUserWorkItem
        |> ignore
        rV
```
I tried to use it and there were number-of-processors Hopac threads + (number-of-processors + some small N) `ThreadPool` threads, not 200 as I wished.

**Comment by polytypic** [comment]
I just tried the following code:

```fs
let inline (^) f x = f x

let numThreads = 100

do ThreadPool.SetMinThreads (numThreads, numThreads) |> printfn "%A"
do ThreadPool.SetMaxThreads (numThreads, numThreads) |> printfn "%A"

do Stream.generateFun 0L
     <| (>) 10000L
     <| (+) 1L
     <| id
   |> Stream.mapPipelinedJob numThreads ^ fun i -> 
        Job.onThreadPool ^ fun () ->
          Thread.Sleep 200
          i
   |> Stream.foldFromFun (0, 0L) ^ fun (count, sum) i ->
        if count % 100 = 0 then
          printfn "%A" ^ ThreadPool.GetAvailableThreads ()
        (count + 1, sum + i)
   |> run
   |> printfn "%A"
```

And after running for some time it uses ~100 ThreadPool threads.  Calling `ThreadPool.SetMinThreads` is important in this toy test, because otherwise the `ThreadPool` does not necessarily grow the number of threads to the desired count.

**Comment by slav** [comment]
A quick side question. How does `Job.onThreadPool` compare to `isolate`? I understand scenarios `onThreadPool` addresses, but can't quite grasp where `isolate` is useful? My first impression was that `isolate` would do similar thing that `onThreadPool` does, specifically allow long-running, blocking jobs to executing without interfering with other jobs, but I was wrong.

**Comment by polytypic** [comment]
`isolate` is a workaround for a lack of a way for workers to uncooperatively steal work from other workers in the current Hopac scheduler.  You would use it in cases where you only have a fairly small number of items of work to process in parallel and the processing of an item is done synchronously and takes relatively long.  Workers in Hopac share work cooperatively.  When executing a block of synchronous code, a worker thread cannot deal out items of work from its private stash to other workers.  If those other workers run out of work, they will starve.  `isolate` basically moves all items of work from the local stash of a worker to a global stash shared by all workers.   This kind of precaution is less important when there is plenty of items to process and the processing of an item take a relatively short amount of time.

**Comment by slav** [comment]
Please correct me if I'm wrong, but here's how I understand Hopac works:
1. When app begin to use Hopac, a number of worker threads equal to number of cores (default) is created. Usually all Hopac jobs are executed on those threads, but job can be executed on local thread if started via `start`. In those cases eventually jobs would migrate to one of the Hopac worker threads (for example when the jobs begins to wait for input from channel, but there're other circumstances when that can happen). It's also possible to push job to Hopac thread via `switchToWorker`
2. When job is to be executed on Hopac thread, it's put in a queue of jobs (stash) by the scheduler. There's a separate stash per each thread.
3. Each job executes to completion. While it's running on Hopac worker thread, no other job can be launched on that thread. In effect the job blocks the thread. Thus the need for jobs to be small and cooperative, to free thread up and allow other jobs to execute.
4. `isolate` simply moves jobs stuck behind current job to a global stack to be executed on other Hopac worker threads. It simply "reshufles" jobs, but if there're multiple long-running blocking jobs, they'll take over all Hopac worker threads and no other regular jobs will execute, in which case I need to use `onThreadPool`.
5. Does scheduler take jobs from the global stack and puts them back into stash per worker thread? Or did I get the concept of stash wrong?
