### ISSUE TITLE
Write an example that shows how to replace (hot-swap) a running server

### ISSUE THREAD

**Issue by VesaKarvonen** [Hopac/Hopac#13]
Assuming you have a CML style server that takes request messages from a channel then you can make it hot-swappable to a degree quite easily.  Specifically, make the channel be held in a mutable ref cell.  That is, clients send requests to the server only by getting the channel from the ref cell.  The server, on the other hand, has the channel held in a local variable and doesn't touch the ref cell.  To hot-swap the server, simply create a new channel and start a new server that takes messages from the new channel.  Then set the ref cell to point to the new channel.  The old server will finish pending requests and will then be garbage collected as it is no longer accessible to new clients.  Write an elaborated example that shows how this can be done in detail.

**Comment by panesofglass** [comment]
:+1:
