### ISSUE TITLE
Project maintenance and future

### ISSUE THREAD

**Issue by polytypic** [Hopac/Hopac#141]
This project needs new maintainers.  I haven't been using F# or even .Net for any real projects for some time now and I find it difficult to find time and motivation to work on Hopac.

**Comment by haf** [comment]
Perhaps you could hand off to a group of people by going through the source code in a google groups hangout? Then that hangout could be published on youtube and added to the documentation of this project. Right now, the code has a lot of assumptions built in (as it should!), but this makes it harder to understand the trade-offs or even software architecture of it.

Even better, if @dsyme would consider making Hopac an officially supported part of F#, I think we'd have a very strong concurrency story as a community. It would make it "more accepted" to use Hopac in a library when one needs a bit of concurrency, a mailbox or a bounded buffer or ...

**Comment by neoeinstein** [comment]
As with @haf, I'm willing to assist in continuing the maintenance of this project. I've been working to get a better understanding on the internals of Hopac. I am working on streams now. I'd also like to come to a consensus on what needs to be done to put down a stable v1 API: what we think needs work, what @polytypic wanted to see but no longer has time to see through, and see about getting a proper website. Note that I have recently purchased the [hop.ac](http://hop.ac) and [hopac.xyz](http://hopac.xyz), both of which currently redirect to the documentation on Github pages.

**Comment by CarstenKoenig** [comment]
I don't know how helpful I can be or how deep I an dig in but would love to give a helping hand if you need some

**Comment by tamizhvendan** [comment]
@polytypic As @haf mentioned, it would be helpful to have a session on the basics of Hopac and followed by an another session on its internals (like how to start, possible future improvements).

**Comment by iskandersierra** [comment]
I'm almost decided to use Hopac in the future, or any other CSP library for F#. I'm really liking the simplicity of its public interface, however the non-"standard" way of naming things gets me confused every time, so I'm still learning. 

My problem is when I go to the sources to see how things work, it's pretty scary down there. It would help to make implementation assumptions clear in a technical document, so that the rest of the community could collaborate better with this fine piece of art.

By the way, is there any follow up to this thread?

**Comment by haf** [comment]
@iskandersierra It's best-effort right now. We use Hopac extensively at work so I'm going to make sure it's stable and doesn't break APIs.

**Comment by haf** [comment]
@polytypic Do you have time to do a tutorial with me and @neoeinstein the next month?

**Comment by polytypic** [comment]
What kind of tutorial? I have a presentation to make on another topic for 18th of October. After that perhaps. (Also, based on Twitter and GH, it looks like Marcus has also moved on.)

**Comment by haf** [comment]
@polytypic Yes, after that is alright. Can you give a suggestion of a time?

**Comment by erlis** [comment]
Guys, any update on this? Have you guys done any documentation? 

@iskandersierra  it's nice to see you around dude!

**Comment by haf** [comment]
@erlis There's been no tutorial, as Vesa never got back to me. But there are PRs and they are being merged and there's been a 0.4.1 release. Docs are pretty good. There's a branch for introducing ValueTask support, too, feel free to help out there.

**Comment by wallymathieu** [comment]
What about the current pull requests?

**Comment by haf** [comment]
What about them?

**Comment by wallymathieu** [comment]
Should they be merged? Closed?

**Comment by wallymathieu** [comment]
For instance the netcore22 should perhaps be geared towards netcore31 since that's the current LTS?

**Comment by haf** [comment]
They should not be merged because they are outdated; their respective authors should update them.

**Comment by haf** [comment]
Or someone else ;) — wink wink
