### ISSUE TITLE
Stream assigned to module-level value

### ISSUE THREAD

**Issue by pavelhritonenko** [Hopac/Hopac#142]
I think it's quite obvious thing, but I haven't noticed that until faced memory leak. Sample:

    open Hopac
    
    let ctrlC =
        let ch = Ch()
        System.Console.CancelKeyPress.Add (ignore >> Ch.give ch >> run)
        Ch.take ch
    
    type Rec = Rec of int
    
    let stream =
        // fun _ ->
        Stream.indefinitely (Job.result ())
    
    [<EntryPoint>]
    let main argv =
        run <| job {
            do! stream // ()
                |> Stream.iter
                |> Job.start
            do! ctrlC
            return 0
        }

The head of the stream never will be garbage collected because it bound to static member. And since it has reference to the promise with the tail, all values produced by stream wont be garbage collected.

I was wondering if it would possible to prevent such situation with some kind of warnings in runtime.

**Comment by neoeinstein** [comment]
You are correct that `stream` in your code would not be garbage collected, and would eventually consume a lot of memory.

I am not really sure what mechanism that we could use to detect that other than through the profiling APIs. We would need to gain access to the object reference tree and verify that it was from a root that would not be garbage collected. Doing so inline to stream creation would introduce an extra expense to most, if not all stream creations.

Perhaps some documentation could be added to note that `Stream` heads should be referenced only as long as is necessary.

**Comment by polytypic** [comment]
Yes, making a more prominent warning about leaks in the main documentation would be appropriate.

See also the slide [Spacetime Leaks](https://docs.google.com/presentation/d/1Yowsc3MV9xWqHJ3u11B0xYqqqeK368BW_dfZ9_H0WJI/edit#slide=id.g9142b12c1_1_20) and the author notes there (the links to `SafeStream` no longer work as I removed it).

If I would rewrite the documentation on streams today, I'd further emphasize the connection between lazy lists and Hopac's streams.

**Comment by neoeinstein** [comment]
PR added with proposed language.
