### ISSUE TITLE
Server jobs and garbage collection

### ISSUE THREAD

**Issue by slav** [Hopac/Hopac#143]
Hello. I've a question about how/when jobs get garbage collected. In the example below the job runs forever (at least for a little while that I had it running). Is this by design? Are all jobs launched through ```Job.foreverServer``` will run like this, essentially never getting collected? Is there a way to stop the job (from inside or outside) and potentially get it collected?

```F#
    let simpleJob() = job {
        printf "tick\n"
        do! timeOutMillis 1000
    }
    printf "Config %A" config
    run (Job.foreverServer <| simpleJob())
    GC.Collect()
    Console.ReadLine() |> ignore
```

**Comment by polytypic** [comment]
What you have there is an infinite loop that waits for a timeout.  `Job.foreverServer` loops indefinitely as specified.  Also, a live timeout prevents a job from being garbage collected&mdash;there is a pointer from Hopac internals to any live timeouts.  (There is no way the example could be just garbage collected.)  So, you need to provide some explicit termination mechanism.  E.g. pass an alternative to the job that signals that it should terminate.  You can `abort` a server loop, but `abort` has the caveat that it doesn't execute finally blocks (so you need to know that those aren't needed), so it can be clearer to use plain `start`, write a loop, and then exit from the loop when requested to terminate.
