### ISSUE TITLE
Job.fromBeginend does not works with azure windows storage 

### ISSUE THREAD

**Issue by cboudereau** [Hopac/Hopac#157]
Hello,

I would like to use Hopac to not use Tpl for async on windows azure storage.
When I want to use the begin end async api from azure storage a plug to Hopac, it hang. When I do the same works with Async it is ok. 
See below the code to reproduce the problem (you have to install azure storage emulator before).

```fsharp
#r @"..\packages\WindowsAzure.Storage\lib\net45\Microsoft.WindowsAzure.Storage.dll"
#r @"D:\packages\Hopac\lib\net45\Hopac.Core.dll"
#r @"D:\packages\Hopac\lib\net45\Hopac.dll"

open System
open Microsoft.WindowsAzure.Storage
open Microsoft.WindowsAzure.Storage.Blob

open Hopac

let devClient = CloudStorageAccount.DevelopmentStorageAccount.CreateCloudBlobClient()

let container = devClient.GetContainerReference("test")

let b (x,y) = container.BeginCreateIfNotExists(x, y) :> IAsyncResult
let e x = container.EndCreateIfNotExists(x)

let ms = new System.IO.MemoryStream()

let b1 (x,y) = ms.BeginWrite("hello"B, 0, 5, x, y)
let e1 x = ms.EndWrite(x)


Async.FromBeginEnd(b, e) |> Async.RunSynchronously //OK

Job.fromBeginEnd b e |> run //Process Begin and hang...
Job.fromBeginEnd b1 e1 |> run //OK
```

**Comment by haf** [comment]
Can I install that on OS X?

**Comment by cboudereau** [comment]
No but you can use a free account instead using emulator.

Thank you!

**Comment by haf** [comment]
My guess is that the underlying API doesn't fulfil the full IAsyncResult contract. It's often that people take shortcuts in libraries. None the less, it's not an issue with Hopac, because I've used this API wrapper extensively without any issues (besides when the client lib in use has issues, like doing blocking things).
