### ISSUE TITLE
Building with .Net Core doesn't work

### ISSUE THREAD

**Issue by haf** [Hopac/Hopac#158]
```
USE=netcore ./run clean build
Restoring dependencies
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
```

From the README

**Comment by polytypic** [comment]
Yeah.  You are using a later version of MSBUILD than the one that was used when the .Net Core port was done.  (I haven't tried later .Net Core versions.)

**Comment by haf** [comment]
I see, thanks. I'll just chillax a bit more on mono then. :) Feeling utterly lost in the .Net Core landscape.
