### ISSUE TITLE
Hopac + ZeroMQ Question 

### ISSUE THREAD

**Issue by krgn** [Hopac/Hopac#159]
Hi, 

first off, sorry for filing an issue here, but I wasn't sure what is
the best way of asking a question related to `Hopac`, so here it is. I
suspect that I am overlooking something important related to `Hopac`
internals, but it could be a different issue altogether. I tried to keep in
mind that `Hopac` jobs should not block on, e.g., IO for long times to 
keep the machine well-greased (see the 100ms timeouts on polling). 
I am not sure how to debug `Hopac` internals, so it would be interesting 
to me learn how to hunt down those kinds of issues.

### The Setup

So, I am experimenting with the following setup, in which there is a
`ZeroMQ` `IServer` component accepting connections and routing them to
back-end workers, which, in turn, queue up request on a `Mailbox` to be
processed downstream. Additionally, there is a simple client which
issues requests, and a root level handler which simply reverses the 
request payload and returns it.

### The Issue

The issue I'm seeing is that if I start the client independently of
the server, the client works as expected (i.e. it enters the loop,
takes requests, times out as expected and generally works). Yet, if I
start the server _before_ the client, the *client never executes its
inner server loop* and *blocks infinitely on a request*. It looks as
if this is a `Hopac` issue, because I have another, similar setup with
`Hopac` involving a slightly different client/server setup (using a
`REP`/`REQ` pair) that works as expected. I can also post that if 
needed.

### Reproduce

To reproduce, the followng snipped can be used:

```fsharp
let ctx = new ZContext()

let mutable respond = true

let handler (request: Request) (handler: ResponseHandler) =
  if respond then
    let chars = request.ToCharArray()
    Array.Reverse chars
    let response = String chars
    handler response

let server = Server.create 4 ctx handler // start a server with 4 workers
let client = Client.create ctx           // start a client instance

client.Request "ohai" // blocks indefinitely
```

To demonstrate why I believe something on the Hopac side is not
working correctly this snipped should normally print _hello_ after one
second, but doesn't. Additionally, when broken up into separate processes,
both client and server work as expected.

```fsharp
job {
  do! timeOut (TimeSpan.FromSeconds 1.0)
  printfn "hello"
} |> Hopac.start
```

### Expected Behavior

The client should start its inner loop and issue requests.

### Code

```fsharp 
open Hopac
open Hopac.Infixes
open ZeroMQ
open System
open System.Threading
open System.Diagnostics

//   ____                _              _
//  / ___|___  _ __  ___| |_ __ _ _ __ | |_ ___
// | |   / _ \| '_ \/ __| __/ _` | '_ \| __/ __|
// | |__| (_) | | | \__ \ || (_| | | | | |_\__ \
//  \____\___/|_| |_|___/\__\__,_|_| |_|\__|___/

module Constants =
  let backend = "inproc://backend"
  let frontend = "tcp://127.0.0.1:5555"

//  _   _ _   _ _
// | | | | |_(_) |___
// | | | | __| | / __|
// | |_| | |_| | \__ \
//  \___/ \__|_|_|___/

[<AutoOpen>]
module Utils =

  let timedOut (timer: Stopwatch) =
    if timer.ElapsedMilliseconds > 1000L then
      timer.Stop()
      true
    else false

  let dispose (t: 't when 't :> IDisposable) =
    try  (t :> IDisposable).Dispose()
    with | _ -> ()

type Request = string
type Response = string
type ResponseHandler = string -> unit

//   ____ _ _            _
//  / ___| (_) ___ _ __ | |_
// | |   | | |/ _ \ '_ \| __|
// | |___| | |  __/ | | | |_
//  \____|_|_|\___|_| |_|\__|

type IClient =
  inherit IDisposable
  abstract Request: Request -> Response

module Client =

  type private ClientState(ctx: ZContext) =
    let id = Guid.NewGuid()

    let req:Ch<string * IVar<string>> = Ch()
    let poll = ZPollItem.CreateReceiver()

    [<DefaultValue>]
    val mutable Socket: ZSocket

    member state.Id
      with get () = id.ToByteArray()

    member state.Req
      with get () = req

    member state.Poll
      with get () = poll

    member state.Start() =
      let socket = new ZSocket(ctx, ZSocketType.DEALER) // DEALER
      socket.Identity <- id.ToByteArray()
      socket.Linger <- TimeSpan.FromMilliseconds(1.0)
      socket.Connect(Constants.frontend)
      state.Socket <- socket

    member state.Restart() =
      dispose state
      state.Start()

    interface IDisposable with
      member self.Dispose() =
        dispose self.Socket

  let private loop (state: ClientState) = job {
      printfn "[client] waiting for request"

      let! (payload, ivar) = Ch.take state.Req

      let mutable error = ZError.None
      let t = Nullable(TimeSpan.FromMilliseconds 1.0)

      use msg = new ZMessage()
      msg.Add(new ZFrame(state.Id))
      msg.Add(new ZFrame(payload))

      printfn "[client] sending request"
      let result = state.Socket.Send(msg, &error)

      if result then
        let mutable incoming = Unchecked.defaultof<ZMessage>

        let timer = new Stopwatch()
        timer.Start()

        printfn "[client] waiting for reply"
        while not (state.Socket.PollIn(state.Poll, &incoming, &error, t)) && not (timedOut timer) do
          do! timeOut (TimeSpan.FromMilliseconds 1.0)

        if timedOut timer then
          printfn "[client] timeout"
          do! IVar.fill ivar "error"
        else
          let response = incoming.[0].ReadString()
          printfn "[client] got a response"
          do! IVar.fill ivar response
      else
        printfn "[client] sending unsuccessful"
        do! IVar.fill ivar "error"

      return state
    }

  let create (ctx: ZContext) =
    let state = new ClientState(ctx)
    state.Start()

    printfn "[client] starting server loop"

    loop
    |> Job.iterateServer state
    |> Hopac.start

    printfn "[client] returning"

    { new IClient with
        member client.Request (request: Request) =
          job {
            let ivar = IVar()

            printfn "[client]] passing request to loop"
            do! Ch.give state.Req (request, ivar)

            printfn "[client]] waiting for response from loop"
            let! result = IVar.read ivar

            return result
          }
          |> Hopac.run

        member client.Dispose () =
          dispose state }

//  ____
// / ___|  ___ _ ____   _____ _ __
// \___ \ / _ \ '__\ \ / / _ \ '__|
//  ___) |  __/ |   \ V /  __/ |
// |____/ \___|_|    \_/ \___|_|

type IServer =
  inherit IDisposable

module Server =

  type IWorker =
    inherit IDisposable

  type Workers = IWorker array
  type RequestPipeline = Mailbox<Request * (Response -> unit)>

  type private ServerState =
    { Frontend: ZSocket
      Backend: ZSocket
      Workers: Workers
      Mailbox: RequestPipeline }

    interface IDisposable with
      member self.Dispose() =
        Array.iter dispose self.Workers
        dispose self.Frontend
        dispose self.Backend

  module private Worker =
    type private WorkerState(ctx: ZContext, mb: RequestPipeline) =
      let timeout = Nullable(TimeSpan.FromMilliseconds 100.0)
      let poll = ZPollItem.CreateReceiver()

      [<DefaultValue>]
      val mutable Socket: ZSocket

      member worker.Poll
        with get () = poll

      member worker.Timeout
        with get () = timeout

      member worker.Mailbox
        with get () = mb

      member worker.Start() =
        worker.Socket <- new ZSocket(ctx, ZSocketType.DEALER)
        worker.Socket.Connect(Constants.backend)

      interface IDisposable with
        member self.Dispose() =
          dispose self.Socket

    let private handle (var: IVar<Response>) (response: Response) =
      response |> IVar.fill var |> Hopac.queue

    let private loop (state: WorkerState) = job {
      let mutable error = ZError.None
      let mutable incoming = Unchecked.defaultof<ZMessage>

      if state.Socket.PollIn(state.Poll, &incoming, &error, state.Timeout) then
        let ident = incoming.[1].Read()
        let str = incoming.[2].ReadString()

        let var = IVar()
        do! Mailbox.send state.Mailbox (str, handle var)

        let timer = Stopwatch()
        timer.Start()

        while not (IVar.Now.isFull var) && not (timedOut timer) do
         do! timeOut (TimeSpan.FromMilliseconds 1.0)

        if timedOut timer then
          printfn "[worker] timeout on backend"
        else
          let! response = IVar.read var

          use reply = new ZMessage()
          reply.Add(new ZFrame(ident))
          reply.Add(new ZFrame(response))

          if state.Socket.Send(reply, &error) then
            printfn "[worker] replied successfully"
          else
            printfn "[worker] error sending response %O" error
      else
        if error <> ZError.EAGAIN then
          printfn "[worker] error during poll %O" error

      return state
    }

    let private onRequest (cb: Request -> ResponseHandler -> unit) (mb: RequestPipeline): Job<RequestPipeline> =
      Mailbox.take mb >>= fun (request, handler) ->
        cb request handler
        Job.result mb

    let create (mb: RequestPipeline) (ctx: ZContext) (cb: Request -> ResponseHandler -> unit) =
      printfn "[worker] starting"

      let state = new WorkerState(ctx, mb)
      state.Start()

      onRequest cb
      |> Job.iterateServer mb
      |> Hopac.start

      loop
      |> Job.iterateServer state
      |> Hopac.start

      { new IWorker with
          member server.Dispose() =
            dispose state }


  let create (n: int) (ctx: ZContext) (handler: Request -> ResponseHandler -> unit)  =
    let mailbox = RequestPipeline()

    printfn "[server] creating frontend"
    let frontend = new ZSocket(ctx, ZSocketType.ROUTER)
    frontend.Bind(Constants.frontend)

    printfn "[server] creating backend"
    let backend = new ZSocket(ctx, ZSocketType.DEALER)
    backend.Bind(Constants.backend)

    printfn "[server] creating worker"
    let workers = new ResizeArray<IWorker>()
    for n in 0 .. n - 1 do
      let worker = Worker.create mailbox ctx handler
      workers.Add worker

    let thread = new Thread(fun () ->
      printfn "[server] setting up proxy"
      // proxy messages
      let mutable err = ZError.None
      if not (ZContext.Proxy(frontend, backend, &err)) then
        printfn "[server] error during proxy setup %O" err
        ZException(err) |> raise
      printfn "[server] proxy not started: %O" err)
    thread.Start()

    printfn "[server] startup done"
    let state =
      { Frontend = frontend
        Backend = backend
        Workers = workers.ToArray()
        Mailbox = mailbox }

    { new IServer with
        member self.Dispose() =
          dispose state }
```

Thank you for any hints!

Karsten

**Comment by neoeinstein** [comment]
I have a theory that largely stems from the use of a non-yielding call to the C# ZeroMQ library. While the call is done by polling, it does not yield the thread of execution, thus blocking the executing thread for 100ms at a time. Is there an asynchronous version of the call available from the C# ZeroMQ library?

The second potential issue follows from the use of `Hopac.start` to start the workers in combination with there not being a path that yields in all cases. `Hopac.start` executes on the thread it was called from. This execution continues until it hits a blocking point. In the case of the server starting before the client, no message will be waiting on the first poll. This causes the job to go down the else branch, ultimately looping on itself. Because that path has no point where it yields execution, it executes forever, effectively stopping progress.

To test this theory, try throwing a `do! Hoapc.idle` after the test against `EAGAIN` in the server worker. It would also be helpful to get a printout of the logs from your execution of the test. (Though you may want to add a log which indicates when no message was received and we are, therefore, looping.) I'd also encourage you to use a polling timeout of 0ms (making the call return instantly if a message isn't ready) if you can't find an asynchronous version of the ZeroMQ call. You want to avoid calls that synchronously wait on the Hopac thread if possible.

Let me know if this changes anything for you.

**Comment by pblasucci** [comment]
Good points, @neoeinstein. As far as I know, there are no yielding operations on `clrzmq4`. However, I think you suggestion of an immediate return on polling is probably the right way to good. Alternately, there's the overloads of `Send` and `Receive` which take flags. There's a ZMQ flag for "don't wait" which amounts to the same thing as "poll with immediate return". Of course, the downside is, one then has to explicitly manage the re-attemping.

**Comment by polytypic** [comment]
As [mentioned in a previous issue](https://github.com/Hopac/Hopac/issues/10#issuecomment-74420560), I would try to run the ZMQ poll loop in a dedicated thread (that is not one of the Hopac worker threads).  It should be possible to set things up so that one can send messages to the ZMQ poller thread from Hopac jobs.  IOW, send messages to the ZMQ poller thread from within the same process.  To build such a communication mechanism, what you fundamentally need is a way to force the ZMQ poll call to return when it should process a message coming from within the process.  In the worst case you should be able to achieve that by sending a (possibly zero length) ZMQ message.  Once you have a mechanism to make the ZMQ poll call return, you can make the ZMQ poller thread to check for incoming messages from a shared queue.  To send replies from ZMQ poll thread you can just use ordinary Hopac abstractions (IVar, Mailbox, Ch, ...).

**Comment by polytypic** [comment]
Note that polling like this is not recommended:

```fs
        while not (IVar.Now.isFull var) && not (timedOut timer) do
         do! timeOut (TimeSpan.FromMilliseconds 1.0)
```

You can just say:

```fs
    timeOutMillis 1000 ^-> fun () -> printfn "Timed out ..."
<|> var ^=> fun response -> // ...
```

**Comment by krgn** [comment]
So after recovering from some weird stomach bug, I tried some of your suggestions. The problem was mostly fixed by adding `Hopac.idle` (as per @neoeinstein 's suggestion) in `else` case in the worker loop, when there are not messages to be processed. This change and your explanations with respect to the _cooperative threading model_ makes much more sense to me now, thx!

@polytypic I wonder if you could explain briefly why you recommend to move the polling part out of `Hopac` jobs, even when tuning the polling for very low timeout values. Is this because this introduces too much latency? The thing that I am worried about is that, if polling is moved into a separate thread, I'll run into thread-safety issues with the sockets, where I might end up sending and polling on the same socket at the same time, which cannot happen if I process polling/sending inside the same `Hopac` job. The obvious solution to that would be to be to move sending into that thread as well, but then I am more or less back where I am right now, managing sockets on threads manually.

**Comment by haf** [comment]
Here's a sample that can push 4000+ data points a second. https://github.com/logary/logary/blob/master/src/services/Logary.Services.Rutta/Rutta.fs on a beefy machine (40 cores) at total=2% CPU usage)

**Comment by haf** [comment]
Closing because I think this has been answered.
