### ISSUE TITLE
Wrapping EventStore Action callback with hopac

### ISSUE THREAD

**Issue by btrepp** [Hopac/Hopac#166]
I've been trying to get my head around hopac and I'm trying to integrate it with Eventstore, specifically the Persistent subscriptions.

Eventstore can fire an Action<_,_> when new events have arrived, and I was trying to abstract that around something that feels more functional.

Here's what I have come up with, but I'm not sure if this is 
1) Proper usage of Hopac
2) An incorrect problem to use hopac for (eg should i use async instead)

```
    open Hopac
    type Server = 
        private {
            onEvent : Ch<EventStore.ClientAPI.ResolvedEvent>
            finished: IVar<unit>
        }

    let startServer (s,g) (con:EventStore.ClientAPI.IEventStoreConnection): Job<Server> = 
            job{
                let server = {onEvent= Ch();finished= IVar()}
                let onevent = new System.Action<_,_>(fun _ e ->  Ch.give server.onEvent e |> queue)
                let onerror  =new System.Action<_,_,_>(fun _ _ e -> IVar.fillFailure server.finished e |> queue)
                do! Job.Ignore <| (Job.fromTask <| fun () -> con.ConnectToPersistentSubscriptionAsync (s,g,onevent,onerror))
                return server
            }

    let getValue (server:Server) : Alt<EventStore.ClientAPI.ResolvedEvent> = server.onEvent |> asAlt

    //Usage
    let usecase1 :Job<unit>= startServer(stream,group) (connection) 
                            >>= fun s -> Job.foreverServer (getValue s >>= furtherprocessing)
```

This would be the simplest case, from there I could possibly build up a mailbox server or even Nack-aware server (and sending this back to ES).

**Comment by haf** [comment]
`queue` possibly interleaves, so you should prefer `start`.

We've abstracted eventstore subscriptions as Stream in our project.

**Comment by haf** [comment]
BTW; if it works and you've tested it, you're probably fine.
