### ISSUE TITLE
single-threaded workstation garbage collection (with gcServer enabled="true")

### ISSUE THREAD

**Issue by bradder555** [Hopac/Hopac#173]
Hi All

I've noticed this in a couple of places
Using .net 4.5.1 and dotnet core 2

I'm getting the warning "single-threaded workstation garbage collection..."

my app.config is
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <gcServer enabled="true"/>
</configuration>
```

The code that i'm running is straight out of the examples
```
open System
open Hopac.Hopac;
open Hopac.Infixes;

let rec fib n = job {
  if n < 2L then 
    return n
  else 
    let! (x, y) = fib (n-2L) <*> fib (n-1L)
    return x + y
  }

[<EntryPoint>]
let main argv =
    fib 3000L |> run
    0 // return an integer exit code
```

The app.config file is being copied and renamed in the bin folder, I'm not sure what else to try.

Thanks
Brad

**Comment by haf** [comment]
Yes? That's how app.configs work?

**Comment by bradder555** [comment]
Exactly, everything is as expected, but I'm still getting the warning

**Comment by 0x53A** [comment]
gcServer must be below runtime: https://msdn.microsoft.com/de-de/library/ms229357(v=vs.100).aspx

example: 

```xml
<configuration>
   <runtime>
      <gcServer enabled="true"/>
   </runtime>
</configuration>
```

**Comment by bradder555** [comment]
Ahh face palm, thanks 0x53A
