### ISSUE TITLE
Memory leak with Alt.choose and Stream.indefinitely

### ISSUE THREAD

**Issue by TheAngryByrd** [Hopac/Hopac#174]
Hopac 0.3.23

Similar to https://github.com/Hopac/Hopac/issues/139

Seems the ordering matters 

```Fsharp
open Hopac
open System

let ctrlC =
    let ch = Ch()
    System.Console.CancelKeyPress.Add (ignore >> Ch.give ch >> run)
    Ch.take ch

let error = IVar<int>()

let mb = BoundedMb<int>(10)

// No leak
// let foreverResult = 
//     Alt.choose [
//         BoundedMb.take mb 
//          ]

// No leak
// let foreverResult = 
//     Alt.choose [
//         error :> Alt<_>
//         BoundedMb.take mb 
//          ]

// leak
let foreverResult = 
    Alt.choose [
        BoundedMb.take mb 
        error :> Alt<_>
         ]

[<EntryPoint>]
let main argv =
    run <| job {
        let random = new Random()
        do!
            random.Next(10000)
            |> BoundedMb.put mb 
            |> Job.foreverServer
            |> Job.start
        do! 
            foreverResult
            |> Stream.indefinitely 
            |> Stream.iter
            |> Job.start
        do! ctrlC
        return 0
    }
```

**Comment by haf** [comment]
Have you investigated how this can be solved?

**Comment by TheAngryByrd** [comment]
No, I should test with https://github.com/Hopac/Hopac/pull/140 to see if that is the fix that's needed.

**Comment by haf** [comment]
@TheAngryByrd I've merged it now, but it seemingly broken travis and I don't have the cycles to spare to fix this right now. Could you have a look, please?

**Comment by TheAngryByrd** [comment]
```
/home/travis/build/Hopac/Hopac/Libs/Hopac/Hopac.fs(1642,24): error FS0001: The type 'System.Threading.Lock' is not compatible with the type 'Hopac.Lock' [/home/travis/build/Hopac/Hopac/Libs/Hopac/Hopac.fsproj]
/home/travis/build/Hopac/Hopac/Libs/Hopac/Hopac.fs(1642,24): error FS0193: Type constraint mismatch. The type     'System.Threading.Lock'    is not compatible with type    'Hopac.Lock' [/home/travis/build/Hopac/Hopac/Libs/Hopac/Hopac.fsproj]
/home/travis/build/Hopac/Hopac/Libs/Hopac/Hopac.fs(1644,24): error FS0001: The type 'System.Threading.Lock' is not compatible with the type 'Hopac.Lock' [/home/travis/build/Hopac/Hopac/Libs/Hopac/Hopac.fsproj]
/home/travis/build/Hopac/Hopac/Libs/Hopac/Hopac.fs(1644,24): error FS0193: Type constraint mismatch. The type     'System.Threading.Lock'    is not compatible with type    'Hopac.Lock' [/home/travis/build/Hopac/Hopac/Libs/Hopac/Hopac.fsproj]
```

Just looks like its being stubborn about namespacing.  I'll send a PR

**Comment by haf** [comment]
Thanks. May I ask how much you tested this PR? We have a pretty stable system using Hopac and would prefer not to include any changes to the core that possibly causes corruption, but of course; a bugfix that stop a memory leak is great. 

As a tangent; do you understand the PR's code? Because I don't, to be honest.

**Comment by TheAngryByrd** [comment]
> Thanks. May I ask how much you tested this PR? We have a pretty stable system using Hopac and would prefer not to include any changes to the core that possibly causes corruption, but of course; a bugfix that stop a memory leak is great.

I tested this PR 
1. creating a project referencing the Hopac main projects
2. Testing out the above code to see the behavior
3. Switching branches (also rebasing it onto master ) 
4. Testing again and checking.

I could potentially write a test that looks for memory size thresholds.  Think that would be beneficial?

> As a tangent; do you understand the PR's code? Because I don't, to be honest.

I do not entirely.  What it seems like is it's looping through the entire list of possible Alts to work and removing anything that hasn't been `Picked`. Which I would guess in my case would be the `error :> Alt<_>` since it's was never chosen.

I do plan on diving deeper into Hopac more and more since I'm relying on it for many projects I use internally now.

**Comment by TheAngryByrd** [comment]
Also think its worth releasing an alpha on nuget? If it breaks downstream we can always unlist it.

**Comment by haf** [comment]
@neoeinstein @polytypic Could either of you give me and @TheAngryByrd access to push the nuget? My nuget email is henrik at qvitoo dot com.

**Comment by haf** [comment]
Merged to master now. Closing, will release this.
