### ISSUE TITLE
Build process doesn't work on windows because of 'rm -rf'

### ISSUE THREAD

**Issue by Szer** [Hopac/Hopac#187]
This little line ruins everything on machines without bash :)

https://github.com/Hopac/Hopac/blob/72de32046f073d870655dc9203419470dc73e307/build.fsx#L43

There is `Directory.delete(path)` for FAKE 5 in `Fake.IO.FileSystem` module to make this target works in every OS

https://fake.build/apidocs/v5/fake-io-directory.html

**Comment by Szer** [comment]
Actually `Fake.IO.FileSystem` is already installed because it is transitive dependency for a lot of other modules.

So maybe I'm missing something obvious, but can't we just
change `exec "rm" "-rf .gh-pages" ` to `Directory.delete ".gh-pages"`

**Comment by haf** [comment]
PR away, there's nothing sacred about my fake script.
