### ISSUE TITLE
Problems with network stream

### ISSUE THREAD

**Issue by nanodesu88** [Hopac/Hopac#190]
Hello. I need some help. My english is not good, sorry me
Im trying to realise tcp client-server messaging with Hopac.
I am using IVar for event system. Is this fine or? Anyway it is a not main question.

When i creating a client, i create and attach IVar to him. In concurrent job i am waiting for this IVar (IVar.read), and then client can be continue work. Then, when cliens receiving a ``connect response`` packet im trying to IVar.fill attached IVar. Looks pretty simple, but something goes wrong.

Here is code: 
https://gist.github.com/nanodesu88/15199957bb2cc99b82c6f12102426d88#file-main-fs

and aq.connectVar |> IVar.read does not resolving. 
But if i am moving last line to start of job like this: 

https://gist.github.com/nanodesu88/15199957bb2cc99b82c6f12102426d88#file-fixed-fs

reading a IVar is completed is concurrent job. Looks like networkstream.read is blocking some job, but i does not know how to jobs works inside and can't imagine what can be wrong

**Comment by nanodesu88** [comment]
Update. Here is full code: 
https://gist.github.com/nanodesu88/15199957bb2cc99b82c6f12102426d88

**Comment by haf** [comment]
You're doing blocking work on in a Job; you need to use ReadAsync and the like, or use Job.Scheduler.isolate.

**Comment by nanodesu88** [comment]
Hmm... so why if i add second IVar, first one start works well?
https://gist.github.com/nanodesu88/15199957bb2cc99b82c6f12102426d88#file-strange-fs

**Comment by haf** [comment]
Probably because the threading model in Hopac is cooperative; adding more concurrency primitives reorders the implicit schedule that these green threads execute with.

**Comment by nanodesu88** [comment]
Okay. Can you explain a isolate version of my code please?

**Comment by haf** [comment]
I can sell you two hours of consulting time if you want.

**Comment by nanodesu88** [comment]
It would be nice, but my english very bad and i probably can understand about 10% of ur lessons :blush:

**Comment by haf** [comment]
Haha, well, I think your english is good enough to understand, so I doubt that would be a problem. =) If you're interested; henrik at haf.se is my e-mail.
