### ISSUE TITLE
Handling exceptions

### ISSUE THREAD

**Issue by nanodesu88** [Hopac/Hopac#191]
Why this https://gist.github.com/nanodesu88/7748e533a5e6d8bfeeb6062124f030ff anyway raises an unhandled exception?

**Comment by haf** [comment]
I'm not sure, I haven't used `abort`, before. Leaving this question open.

**Comment by nanodesu88** [comment]
Look at https://gist.github.com/nanodesu88/7748e533a5e6d8bfeeb6062124f030ff#file-f-fs f.fs file. Can we handle exceptions in child job?

**Comment by haf** [comment]
Exceptions are handled well with `tryWith`; that one I'm using a lot. Can't you try returning `unit` instead?

**Comment by haf** [comment]
BTW, if you `queue` things, they are no longer running on the job you're wrapping with a try handler.

**Comment by nanodesu88** [comment]
So we can't handling all the child jobs in one place?

**Comment by haf** [comment]
I haven't used child jobs either. If I need something parallel, I `Job.start` it.

I'm saying you can't use `queue` inside a job and expect the queued job to fail the started-from-job.

**Comment by nanodesu88** [comment]
Thanks you

**Comment by haf** [comment]
```
let errorHandler e = Console.Error.WriteLine(e.ToString())
let xJs = Job.conIgnore [ logThings; startWebServer; things ]
Job.tryIn xJs errorHandler
```

**Comment by haf** [comment]
You're welcome
