### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by varon** [Hopac/Hopac#195]
How's the netcore support?

Would you consider this stable enough for production usage?

**Comment by haf** [comment]
Yes, it's very stable and has been running in our prod without issues for the last three years.

**Comment by haf** [comment]
> How's the netcore support?

The codebase could use a PR to support ValueTask and perhaps there are some synergies to be found in the new async machinery of .net core, but besides ValueTask, I'm not sure there is.

**Comment by varon** [comment]
Thanks a ton for the answers.

When is 1.0 planned?

**Comment by haf** [comment]
> When is 1.0 planned?

I think it make sense to release it once:

- we've added a global error handler with logging
- we've added support for ValueTask

And optionally:

- allowing different schedulers to avoid one bit of a monolithic system to crowd out another bit of a monolitic system
- making it easier for programmers to catch their mistakes with JobBuilder.Zero()

There are issues for these in this repo. I haven't allocated any time to this right now, but this was my plan.

**Comment by varon** [comment]
Thanks, that's really good to hear.
