### ISSUE TITLE
How to convert to task?

### ISSUE THREAD

**Issue by cmeeren** [Hopac/Hopac#197]
Probably a stupid question, but I need to convert a `Job` to a `Task` because I'm using Giraffe, which is using `Task` for its `HttpHandler`s. How can I convert a job to a task? I can't find any functions in `Job` with the right signature (I can only find functions from `Task` to `Job`, not the other way).

**Comment by haf** [comment]
Is it a fire-once task then? A Promise maps well to it. You need a TaskCompletionSource, and then something like

```fsharp
module Job =
  let startAsTask (xJ: Job<_>) =
    let tcs = new TaskCompletionSource()
    start (xJ >>= Job.catch >>- function Choice1Of2 x -> tcs.SetResult x | Choice2Of2 e -> tcs.SetException e)
    tcs.Task
```

**Comment by cmeeren** [comment]
Thanks! I may not properly understand `Job` or Hopac; I'm currently experimenting with replacing all internal `Async` stuff in a framework of mine with `Job` to see if I get better performance (there's a lot of lifting non-async user code to `Async` all over the place which causes a bunch of allocations etc.)

**Comment by haf** [comment]
Job is like a cold observable that only yields once, and can either return a value, never return anything (run forever) or throw an exception when unwrapped/bound

**Comment by cmeeren** [comment]
Thanks. There seems to be a bug in the code you posted; `'x` is constrained with `required 'x :> Job<'x>`.

**Comment by haf** [comment]
Replace the map with a bind and it should resolve

--

**Comment by cmeeren** [comment]
Thanks! Since I'm not used to the infixes, I found the below clearer:

```f#
let startAsTask (xJ: Job<'x>): Task<'x> =
    let tcs = new TaskCompletionSource<'x>()
    job {
      try
        let! x = xJ
        tcs.SetResult x
      with ex -> tcs.SetException ex
    }
    |> start
    tcs.Task
```
