### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by eacasanovaspedre** [Hopac/Hopac#202]
Is Hopac dead? The most recent release is more than two years old. I see almost no recent commits. I know this is not an issue per se, but I like Hopac and I'm worried about using a dead library.
Should I move to plain async code?

**Comment by haf** [comment]
I wouldn't say it's dead, see e.g. https://github.com/logary/logary/pull/444 which uses Hopac. The only two real issues that would be nice, but not urgent, if someone helped to fix would be:

a. ValueTask support
b. Iterating millions with `while` inside a `job` causes a SO exception, so it should be done tail-recursive or similar

So no, it's not dead.
