### ISSUE TITLE
Use bounded quantification at covariant positions for `Job<_>` and `Alt<_>`?

### ISSUE THREAD

**Issue by VesaKarvonen** [Hopac/Hopac#30]
In #29 @vasily-kirichenko ran into a subtyping issue with the `>>=?` combinator.  I wonder if all the combinators in Hopac should be changed to use bounded quantification at covariant positions where a user given function is expected to return a `Job<_>` or an `Alt<_>`?

For example, the current signature of `>>=?` is

```fsharp
val (>>=?): Alt<'x> -> ('x -> Job<'y>) -> Alt<'y>
```

and it would be changed to

```fsharp
val (>>=?): Alt<'x> -> ('x -> #Job<'y>) -> Alt<'y>
```

This is a breaking change in the sense that existing code will need to be modified (e.g. `upcast`s removed sometimes other type ascriptions added) to compile.  I would assume that the amount of client code using Hopac is still small enough that it would not be a major problem.  **Any thoughts on this?**  (If I get no replies, I assume nobody cares and I will just make the change.)

I actually did a test run of this modification locally about a week ago, but I reverted the changes.  It seemed that it is an overall win: to my eyes client code got a little bit simpler with fewer upcasts and other type ascriptions.  The problem in #29 would disappear, for example.  However, it also does change the inferred types in other ways and you will need to add type ascriptions elsewhere.  So, it is not just a clear 100% improvement.

**Comment by VesaKarvonen** [comment]
As you know, I've changed Hopac to use bounded quantification for `Job<_>` and `Alt<_>` types at covariant positions.  How do you find the change?

**Comment by vasily-kirichenko** [comment]
I think client code has become clearer, simpler and more natural: less kinds of operators and combinators, eliminated `Alt`s modules. No issues so far. Thanks.

**Comment by VesaKarvonen** [comment]
Nice to hear that!  I'm closing this issue now, but (anyone) feel free to report issues that you might encounter related to this change.
