### ISSUE TITLE
Differences between Job.delay and job {}

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#36]
I'm struggling to understand why the first server works but the second does not:

```fsharp
let ch = ch<string>()

Job.foreverServer (job {
    let! v = ch
    printfn "from CE job: %s" v })  // only this output works
|> run

Job.foreverServer (Job.delay <| fun _ ->
    ch >>% fun v -> printfn "from plane job: %s" v)  // never prints anything 
|> run

run (ch <-- sprintf "msg")
```

As far as I understand these two servers semantically equal. What am I doing wrong?

**Comment by VesaKarvonen** [comment]
You want `|>>` rather than `>>%`.

`forever` and `foreverServer` and many other combinators ignore the results of jobs given as arguments. This is done to avoid having to wrap the jobs with costly extra code to ignore the results.  This also means that type checking will not catch cases like this.  To be honest, I'm not sure whether the implicit ignore is used frequently enoug to justify the lowered type safety.

**Comment by vasily-kirichenko** [comment]
Thanks!

`ch |>> fun v -> printfn "got: %s" v` has type `Job<unit>`.
`ch >>% fun v -> printfn "got: %s" v` has type `Job<(string -> unit)>`.

I see that I'm really wanted the first, obviously. 

But if code is type checked it should either work or crash with exception. Am I right that `foreverServer` just stops looping if the job returns anything different from `Job<unit>`? It's very fragile for my taste.

**Comment by VesaKarvonen** [comment]
`foreverServer` doesn't stop looping, it just implicitly ignores the result of whatever job it is given.

For example, suppose that you would want to create a sink job that takes (all) messages from a given channel and ignores them.  You could write it like this:

```fsharp
let sink (ch: Ch<'x>) = Job.forever ch
```

As opposed to, for example:

```fsharp
let sink (ch: Ch<'x>) = Job.forever (ch |>> fun _ -> ())
```

The second version, using an explicit ignore, is slower than the first one.

Note that having foul-tasting fragile monadic combinators that implicitly ignore the results of sub-operations is not at all uncommon.  See for example:

* http://www.quanttec.com/fparsec/reference/primitives.html#members.:62::62:..
* http://hackage.haskell.org/package/base-4.7.0.2/docs/Prelude.html#v:-62--62-

There are cases where the implicit ignore can be both convenient and performs better than having to use an explicit ignore.  However, perhaps it would be better to have separate versions of operations that perform the implicit ignore.

**Comment by vasily-kirichenko** [comment]
Thanks, I finally understand it. Yes, implicit ignoring does make sense. However, another set of operators (not operations) would be an overkill.
