### ISSUE TITLE
Add FAKE support

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#43]
Add some FAKE support.

- [ ] build everything in release configuration
- [ ] create and publish NuGet package(s)

**Comment by vasily-kirichenko** [comment]
@VesaKarvonen what is the minimum setup for building `Hopac.Platform.iOS` and `Hopac.Platform.Android`? Is it possible to build them under windows?

**Comment by VesaKarvonen** [comment]
You need Xamarin licenses for both platforms. I think it is best to ignore
them for now.

**Comment by vasily-kirichenko** [comment]
What do think about merging Hopac and Hopac.Extra NuGet packages? Some points:

* In order to have distinct version and release notes for Hopac.Extra it's necessary to add `RELEASE_NOTES_extra.md`
* To have 100% consistent pair of the two packages it's necessary to always create and publish them together.
* Hopac.Extra.dll/pdb/xml is relatively small (~500KB) and will not make Hopac package significantly heavier.

However, if you like to have two packages, I'll do so.

**Comment by VesaKarvonen** [comment]
I don't really have objections to this.  Originally I wanted to emphasize the difference between the core/primitive operations of Hopac (Hopac.dll and Hopac.Core.dll) and abstractions built on top of those (Hopac.Extra.dll and others).  But I'm not sure that is relevant to potential users of Hopac.  In fact, in the future, it might be more practical to move some stuff from Hopac.Extra to Hopac.

**Comment by vasily-kirichenko** [comment]
OK, then I'm adding Hopac.Extra binaries to Hopac package (for now).
