### ISSUE TITLE
FYI: Merging parts of Hopac.Extra to Hopac and the rest to Hopac.Experimental

### ISSUE THREAD

**Issue by VesaKarvonen** [Hopac/Hopac#47]
I'm going to reorganize the libraries somewhat.  I plan to eliminate the `Hopac.Extra` library by moving a number of modules from it to `Hopac` and the remaining modules to `Hopac.Experimental`.  I plan to move the following modules and associated types to `Hopac`:

* `Hopac.Extra.Alt` -> `Hopac.Alt`
* `Hopac.Extra.BoundedMb` -> `Hopac.BoundedMb`
* `Hopac.Extra.Streams` -> `Hopac.Stream` (**Note:** name changed)
* `Hopac.Extra.StreamVar` -> `Hopac.Stream.Var`
* `Hopac.Extra.StreamSrc` -> `Hopac.Stream.Src`
* `Hopac.Extra.StreamsBuilders` -> `Hopac.TopLevel`

The other modules will be moved to `Hopac.Experimental`.  Many of those modules are either rather incomplete (e.g. `Hopac.Extra.Stream`) or unlikely to be really useful (e.g. `DirCh` and `SwapCh`).

This should also make the name of the `Hopac.Extras` library more meaningful.

**Comment by vasily-kirichenko** [comment]
Great plan. It'll make Streams and others more visible. BTW, what about `MChan`? (not that I've already used it, but..)

**Comment by VesaKarvonen** [comment]
I considered `Multicast`, but I it is essentially subsumed by streams.  *Approximately*:

* `Multicast.create` -> `Stream.Src.create`

* `Multicast.port` -> `Stream.Src.tap >> Stream.values`

* `Multicast.multicast` -> `Stream.Src.value`

* `Multicast.recv` -> use the alternative returned by `Stream.Src.tap >> Stream.values`

The fact that `Multicast.multicast` is an alternative is not significant as it is essentially a non-blocking operation (it can be temporarily unavailable, but that is rarely going to be an significant).
