### ISSUE TITLE
Hanging in tests

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#49]
I'm working on tests for `ParallelExecutor` and I cannot understand why https://github.com/Hopac/Hopac.Extras/blob/master/tests/Hopac.Extras.Tests/ParallelExecutorTests.fs#L42 hangs then failed with timeout exception. I suspect that something wrong with the test itself.

**Comment by VesaKarvonen** [comment]
https://github.com/Hopac/Hopac.Extras/blob/master/src/Hopac.Extras/ParallelExecutor.fs#L53

Hmm... [Looking at the code layout only.] Should the above also be executed for failed jobs?

**Comment by vasily-kirichenko** [comment]
OMG. You are right. Thanks! I added parenthesis around the whole `match` and everything work ok now. 
I was absolutely sure that the entire `match` is the right operand for `>>. (workDone <-- result)`. I'm sure that if write, for example:

```fsharp
match x with
| Some x -> x
| None -> 1
|> Option.iter (printfn "%A)
```
then the match result will be piped to `Option.iter`. Am I understand correctly that `>>.` does not work this way?

**Comment by VesaKarvonen** [comment]
It is just the rules that F# has adopted for parsing layout sensitive syntax.  Here is the original snippet:

```fsharp
match result with
| Fail (Recoverable _) -> failedMessages <<-+ msg
| Fail (Fatal _)
| Ok ->
    match completed with
    | Some mb -> mb <<-+ (msg, result)
    | None -> Job.unit()
>>. (workDone <-- result) }
```

In F#, operator at the beginning of a line continues expression on the preceding line as long as it is at most operator width plus 1 columns to the left of the beginning of the preceding line.  So, just make it operator width plus 2.  For example, indent the inner match one more char to the right:

```fsharp
match result with
| Fail (Recoverable _) -> failedMessages <<-+ msg
| Fail (Fatal _)
| Ok ->
     match completed with
     | Some mb -> mb <<-+ (msg, result)
     | None -> Job.unit()
>>. (workDone <-- result) }
```

While it is mostly a win, layout sensitive syntax sometimes does surprising things.

**Comment by vasily-kirichenko** [comment]
Thanks for the explanation! This is a very subtle rule in f#.
