### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#52]
When I `run` my top level `Job` in a console application, the following exception raises:

![untitled](https://cloud.githubusercontent.com/assets/873919/6123868/afadaa84-b118-11e4-9d0d-fa68c4d98ca5.png)

What could cause it?

**Comment by VesaKarvonen** [comment]
This is probably an issue with the initialization logic.  Hopac currently does a bit of micro-optimization in this area.  Can you arrange to call `Hopac.Core.StaticData.Init()` ([see](https://github.com/Hopac/Hopac/blob/master/Libs/Hopac.Core/Engine/StaticData.cs#L14)) before you use any other Hopac code?  Does the problem go away if you do?

I should probably re-benchmark the performance effect of using the normal .Net initialization to see if it makes a significant difference.

**Comment by vasily-kirichenko** [comment]
Yes, it does resolve the problem. 
Interesting that a simpler code runs OK even without `Hopac.Core.StaticData.Init()`.

**Comment by VesaKarvonen** [comment]
Can you post the first few lines that use Hopac?

Basically a number of things, like `Job.unit ()` and `Alt.unit ()`, (unsafely) assume that `StaticData.Init()` has already been called.  This is done to avoid static initialization overhead and doesn't typically cause problems.  I think I got some speed up with that, but I'm not sure how relevant it is at the present.

**Comment by vasily-kirichenko** [comment]
```fsharp
Job.usingAsync (new InputProcessor.Processor()) <| Job.delayWith (fun processor ->
    Console.watch() >>= fun events ->
      let rec loop() = Job.delay <| fun _ ->
        (events.Cancelled >>%? ()) <|>?
        (events.KeyPressed >>=? fun key ->
          match key with
          | ConsoleKey.S -> 
            processor.GetState() >>= fun state ->
            log.Info "%A" state
            loop()
          | _ -> loop())
      loop())
  |> run
```
while the following simpler code works ok:
```fsharp
(Console.watch() >>= fun events ->
    let rec loop() = Job.delay <| fun _ ->
      (events.Cancelled |>>? fun _ -> printfn "Cancelled") <|>?
      (events.KeyPressed >>=? fun key ->
          log.Info "Key pressed: %A" key
          loop())
    loop())
  |> run
```

**Comment by VesaKarvonen** [comment]
In this case the code that accesses static data before init is in `InputProcessor.Processor()`.

**Comment by vasily-kirichenko** [comment]
```fsharp
type Processor() = 
    let updateSettings = ch<unit>()
    let getState = ch<Ch<StateView>>()
    let stop = ivar<unit>()
    
    let rec loadModel settings timeout = 
      (updateSettings >>=? fun _ -> loadModel (loadSettings()) timeout) <|>?
      (getState >>=? fun repCh ->
         repCh <-- { State = sprintf "LoadModel in %A" (TimeSpan.FromMilliseconds(float timeout)) }
         >>. loadModel settings timeout) <|>?
      (timeOutMillis (int timeout) >>=? fun _ ->
         Loader.loadCurrentModel() >>= function
         | Ok model -> normal settings model 0<ms>
         | Fail e -> loadModel settings settings.Timeouts.CannotLoadModel) <|>?
      stop >>%? ()

    // ...more recursive functions here for each state...

    do start (Job.foreverServer (loadModel (loadSettings()) 0<ms>))
    interface IAsyncDisposable with
      member __.DisposeAsync() = IVar.tryFill stop ()
```

**Comment by VesaKarvonen** [comment]
Interesting.  I can't spot out the any problematic calls above.  So, the problem must be somewhere else (or I just can't see it).

At any rate, I'll benchmark the init overhead later this evening and see what effect, if any, it has.

**Comment by vasily-kirichenko** [comment]
BTW, it's frustrating that the stack traces are basically useless to find what code raises an exception.

**Comment by VesaKarvonen** [comment]
Hmm... We should look into what can be done to better preserve stack traces.  I wonder what async does exactly to preserve stack traces?  I recall seeing some mention of difficulties with async stack traces as well.

**Comment by vasily-kirichenko** [comment]
For 
```fsharp
let raising() = failwith "error"
let one() = job { raising() }
let two() = job { 
  let x = 0
  return! one() }

run (two())
```
the stack trace is
```
System.Exception: forwarded ---> System.Exception: error
   at FSI_0006.one@26.Do() in L:\github\Hopac.Extras\src\Hopac.Extras\Scripts\JobChoice.fsx:line 26
   at Hopac.Core.JobDelay`1.DoJob(Worker& wr, Cont`1 xK) in L:\github\Hopac\Libs\Hopac.Core\Flow\Job.cs:line 293
   at Hopac.Core.Worker.RunOnThisThread[T](Scheduler sr, Job`1 tJ, Cont`1 tK) in L:\github\Hopac\Libs\Hopac.Core\Engine\Worker.cs:line 101
   --- End of inner exception stack trace ---
   at Hopac.Scheduler.run[x](Scheduler sr, Job`1 xJ) in L:\github\Hopac\Libs\Hopac\Hopac.fs:line 634
   at <StartupCode$FSI_0008>.$FSI_0008.main@()
Stopped due to error
```
so, it contains the raising line, but not `one()` and `two()` functions.

**Comment by vasily-kirichenko** [comment]
I recall @dsyme made some changes into F# make async stack traces more informative. I think it's worth to look at the changes.

**Comment by vasily-kirichenko** [comment]
Found it https://visualfsharp.codeplex.com/SourceControl/network/forks/dsyme/cleanup/contribution/7550

**Comment by VesaKarvonen** [comment]
FYI, I did a quick test on the init issue and it doesn't seem like it would make a significant difference.  So, I will most likely be changing the init to happen 100% automatically in all cases later this evening.
