### ISSUE TITLE
Task.awaitJob mute exceptions

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#53]
```fsharp
let task: Task<unit> = Task.Factory.StartNew(fun _ -> failwith "error")
task |> Task.awaitJob |> run
```
this code hangs on the second line forever. Is this behavior intentional?

**Comment by VesaKarvonen** [comment]
Thanks for reporting the issue!

Feels silly to not have noticed this issue much earlier. :)

**Comment by vasily-kirichenko** [comment]
Yes, it'd fixed the issue, thanks!
