### ISSUE TITLE
Hopac.Core is not compiled with VS 2015 CTP6

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#55]
FYI:

Error		"csc2.exe" exited with code -1073741568.	Hopac.Core

**Comment by VesaKarvonen** [comment]
I haven't tried VS 2015 yet.  This is a bug in the C# compiler?

**Comment by vasily-kirichenko** [comment]
I think yes. I successfully compiled full Hopac solution in CTP5, but cannot in CTP6.

**Comment by vasily-kirichenko** [comment]
https://github.com/dotnet/roslyn/issues/969
