### ISSUE TITLE
Wishlist?

### ISSUE THREAD

**Issue by VesaKarvonen** [Hopac/Hopac#56]
Looking at downloads of the NuGet packages, it seems that there are at least a few users of Hopac and then there seem to be people watching the project, but not necessarily using it.

I'm wondering.
- What would you like to see in Hopac?
- And in what order of priority?
- Would you be interested in contributing?
- Why aren't you using Hopac?  (Obstacles?)

**Comment by vasily-kirichenko** [comment]
My 2 cents on why Hopac is not as popular. 

I think it's not immediately clear for what tasks Hopac is undoubtedly better than Asyncs / Tasks / MailboxProcessors. A direct comparison (short code snippets + benchmark) would help a lot. You compare Hopac streams vs Rx and the main advantage is that Hopac allows to consume events in functional way while Rx - in imperative. It would be cool to see the same task implemented using the both following with concrete advantages. 

People seem to be happy with various combinations of Asyncs / MP / Rx and don't even see how the code becomes complicated at times.

**Comment by VesaKarvonen** [comment]
So, I guess "more examples" is high on the wanted list.

That is reasonable.  However, coming up with examples that speak to others is hard.  I'd like to see people contribute (ideas for) examples.

Speaking of direct comparisons, I think that there are a few examples already.  For example:

* [BoundedMb](https://github.com/Hopac/Hopac/blob/master/Docs/BoundedMb.md) directly compares Hopac with Async+MP and "bare metal" primitives.  Result: Async+MP was broken.  Hopac version is shortest and more composable than the others.

I don't this is just an isolated example.

* [Notifications stream](https://github.com/Hopac/Hopac/blob/master/Docs/Inverting.md#no-wrapping-locks-over-user-code) shows a tiny example where choice streams compose better than Rx.

Speaking of choice streams vs Rx, I think the real benefits are that

* choice streams are quantifiably simpler and more composable (implementation 500 lines vs 50000 lines; all combinators of lazy streams work as choice stream combinators, but not as Rx combinators),

* make it easier to mix other forms of asynchronous programming with streams (you can just run any async code at any point in a stream), and,

* based on a couple of observations (bugs I've seen people write with Rx), thanks to the pull semantics, work closer to what people want (Rx gives control to the producers, but the user defined actions are in the consumers; choice streams put the consumer in control (throttling, polling, ... work at the consumer's pace, backpressure)).

**Comment by EHotwagner** [comment]
I absolutely agree with Vasily.

Other things i would like to see are:

   - I think you should point out how easy it is to transform async,
   iobservables, tasks... to jobs, streams.. so ppl can start exerimenting
   using things they know.
   - Examples and use cases of elements that have no direct correspondence
   in Async,Rx like IVar, MVar and Latches.
   - Something like
   http://blogs.microsoft.co.il/bnaya/2012/08/12/visual-rx-part-2/ would
   make it very easy to learn and test things. Maybe in Cloudsharper?
   - Rx has some nice testing abilities:
   http://blogs.msdn.com/b/rxteam/archive/2012/06/14/testing-rx-queries-using-virtual-time-scheduling.aspx
   using virtual scheduler. I am not sure how that would translate to not
   stream components. This would also make it possible to test for equivalence
   to rx combinators.

I could help with some documentation, marble diagrams...

**Comment by vasily-kirichenko** [comment]
:+1: for `Latches`, I'm afraid I don't understand what they are for. 
Visual Rx looks very interesting indeed.

**Comment by kolektiv** [comment]
For me, my gaps in understanding are really about the implementation. I'd feel more comfortable if I knew a bit more about how to reason about the scheduler. How does it interact when I call code which "isn't Hopac"? If I want to interact with something like a blocking call, what will that do in Hopac? It's that level of "integration" detail which I find hard to get an intuitive grasp of - so far. Although I'm going to carry on trying, because I think it's worth it!

**Comment by VesaKarvonen** [comment]
@EHotwagner Great ideas, thanks!  And help on documentation would be welcome as well!  I think one of the big problems here is that coming up with examples that mean something to others is not that easy.  I'd prefer to work the other way round.  If someone has a reasonably well defined, but challenging, concurrency problem it would be interesting to see how to solve it with the tools that Hopac provides.  Feel free to pose such problems as issues.

@vasily-kirichenko I added a short note on the use of latches to the [reference](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Latch).

@kolektiv I think those are very important questions.  Why not ask those questions in an issue with perhaps some more details on your potential use cases?  Vasily has asked several questions here and I must say those have been very useful for me to answer as well.  Perhaps at some point I have time to edit those answers into the docs.

**Comment by haf** [comment]
I'm interested in learning better async stream handling; handling that manages back-pressure, resource disposal, lazyness and forwarding-to-other-stream. A pickler-like thing that parses an async stream on the fly and yields tokens on-demand and also handle asynchronous exceptions would be a great example. For example, parsing with the BNF for that Kafka gives https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-TheProtocol would be a great example tied together with fetching from a socket.

And I really need to read that book; but there's so much work to be done, so I can't find the time. However, the above is what would help me.

**Comment by haf** [comment]
A simple HTTP client would be an excellent example.

**Comment by hodzanassredin** [comment]
Hi, from my point of view the main problem is about therminology. Hopac introduces too many new concepts, which are hard to understand from the point of view of a developer who knows standard fshap'r primitives. Mybe you could introduce them orthogonally in terms of standard fsharp features.  It takes me some time to understand main ideas. And it is not clear why I should prefere job to async. I think that you need not only technical examples but some kind of real world samples. For example I found that ring-benchmark in hopac is two times faster than async.  https://t.co/BJMJnmHZDU  But it is not enought. Next step it is show why it matters in some kind of a blog post.  Thread ring is cool for doing stuff like that https://t.co/apm1jgqu3f  https://t.co/x3nGFJDnmm . P.S. Just found streams in hopac and at work we have a lot of code based on rx whith vitrual time and so on. Would be interesting to compare them and probably I will give a feedback.

**Comment by hodzanassredin** [comment]
Checked streams docs and It is incorrect to introduce them as observables it is more like AsynSeq http://tomasp.net/blog/async-sequences.aspx/ And Lath could be introduced as CountdownEvent https://msdn.microsoft.com/ru-ru/library/system.threading.countdownevent(v=vs.110).aspx

**Comment by VesaKarvonen** [comment]
@hodzanassredin Quick note that you might find the following presentation useful on streams: [Inverting Event Streams is a Choice](https://docs.google.com/presentation/d/1Yowsc3MV9xWqHJ3u11B0xYqqqeK368BW_dfZ9_H0WJI/edit?usp=sharing).  There is also an out-of-date document on the idea that I removed earlier [Inverting Event Streams is a Choice with Concurrent Jobs](https://github.com/Hopac/Hopac/blob/1a7c1bac6ae56dc97f89af186049d7f2df4bbc03/Docs/Inverting.md).  The library is now slightly different and I think that there is at least one inaccuracy regarding Rx.  Note that the Hopac documentation only [says](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Stream.Stream) that "Choice streams can be used in ways similar to Rx observable sequences.". It doesn't say that they would be the same.

**Comment by VesaKarvonen** [comment]
Thanks for the feedback @hodzanassredin!

> Hi, from my point of view the main problem is about therminology.  Hopac
> introduces too many new concepts, which are hard to understand from the point
> of view of a developer who knows standard fshap'r primitives.  Mybe you could
> introduce them orthogonally in terms of standard fsharp features.  It takes me
> some time to understand main ideas.

That is a fair point and I guess a difficulty that many people have.

The way I think about Hopac, there aren't that many core concepts:

* `Job`
* `Alt`
* `Ch` and some additional built-in communication mechanisms that could also
  just be written in terms of just `Job`, `Alt` and `Ch`:
  * `Promise`
  * `IVar`
  * `MVar`
  * `Mailbox`
  * `BoundedMb`
  * `Latch`
  * ...
* `Stream` (and some helpers like `Stream.MVar`)

Perhaps structuring the reference differently could help here.

> And it is not clear why I should prefere job to async.  I think that you need
> not only technical examples but some kind of real world samples.

Unfortunately I'm not working on any F# apps at the moment or in the foreseeable future.  Lately I've been working on a small application written in [ClojureScript](https://github.com/clojure/clojurescript) using [Reagent](https://reagent-project.github.io/) and [core.async](https://github.com/clojure/core.async) and running on [Electron](http://electron.atom.io/).  The apps where I've used Hopac are not open-source.  My main motivation with Hopac and related projects at the moment is my interest in concurrent and parallel programming.

> For example I found that ring-benchmark in hopac is two times faster than
> async.  https://t.co/BJMJnmHZDU  But it is not enought.  Next step it is show
> why it matters in some kind of a blog post.  Thread ring is cool for doing
> stuff like that https://t.co/apm1jgqu3f https://t.co/x3nGFJDnmm .

I originally started working on Hopac, because I wanted to structure a build system so that each build item could conceptually be an independent "thread" that could perform async IO.  Using .Net Tasks or F# Async increased the overhead of the app unacceptably (just starting hundreds of thousands of tasks/asyncs that just checked dependencies and did nothing took tens of seconds) and the FIFO scheduling of ThreadPool increased memory usage asymptotically going over main memory limits of the workstations we had (which typically had 8GB to 16GB).

Regarding ring-benchmark, as I noted in the Gist, IMHO it is not accurate to call it a "thread" ring, because there is effectively only a single thread that performs tail calls in sequence.

Also, regarding performance, running "straight line" code, like with the tail call ring, is where Hopac is only 2-3 times faster than Async.  When you mix in spawning of new concurrent jobs and sending messages between those jobs you often see much higher differences in speed.

> And Latch could be introduced as CountdownEvent
> https://msdn.microsoft.com/ru-ru/library/system.threading.countdownevent(v=vs.110).aspx

Note that the term `Latch` is also often used, e.g. [CountDownLatch](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CountDownLatch.html), but it makes sense to note the connection.

**Comment by hodzanassredin** [comment]
Yes we had the same problems during my work in [Remoto](http://myremoto.com/). We naively built our server using tasks and failed. Thread ring example is based on code from [Computer Language Benchmarks Game](http://benchmarksgame.alioth.debian.org/u64q/program.php?test=threadring&lang=fsharp) so it was an attempt to compare exactly this version. Would be interesting to see a doc where job, task and async implementations are compared. Your work with reagent and Electron. is quite interesting. I thought about possibility to build UI in top of Alts(as cancellable units) for undo stuff like in [OM](https://github.com/omcljs/om). P.S. Sorry for offtopic but your work is interesting and it is pity that your are not writing about that. Could you answer somewhere to questions like: Is clojura as good as fsharp? I tried it several times, but it doesnt have a type system(I didn't checked core typed). Is it a real problem in reality? What about scala? what about reagent and om? Why do you choose one and not other? Your work with Electron is also interesting.

**Comment by hodzanassredin** [comment]
About thread ring. Mainly I was inspired by this video https://t.co/x3nGFJDnmm. And decided to check this naive version because I think authors of that video uses this kind of thread ring for tests.
