### ISSUE TITLE
Can hopac replace TPL dataflow library (action block in particular)?

### ISSUE THREAD

**Issue by seemantr** [Hopac/Hopac#60]
First of all congratulations on your amazing work around Hopac. The library looks great.

I am trying to introduce it in our codebase in a limited manner to evaluate it. One thing which we heavily rely on in our code is TPL Dataflow library. I was wondering if Hopac can be used to replace Dataflow action block. Don't want all the functionality that Dataflow provides. I am simply looking for an Actionblock replacement. For me the following two capabilities are important:

1. Back pressure so that there are only limited number of outstanding jobs (maybe bounded mailbox can cover this)
2. Ability to parallelize all the jobs/tasks transparently as in the case of Action block. 

All my jobs are very light weight in nature and short running, hence ideal candidate to be used alongside tpl. I don't even need complete code example but anything  that could point me in the right direction. Once I have this I would like to compare the performance againt the tpl action block. I am inclined towards Hopac as it seems like a more natural fit in functional paradigm.

**Comment by VesaKarvonen** [comment]
> Can Hopac replace TPL Dataflow?

Hopac does not provide exactly the same building blocks as TPL Dataflow.

However, you can certainly implement dataflow networks using Hopac.  There is a section "Process networks" in the "Concurrent Programming in ML" book.  It is most unfortunate that the book is not freely available.

I doubt that just replacing ActionBlock with something from Hopac would bring much benefits.  The model that Hopac provides is different and for best results you will likely need to architect the program differently.

There seem to be several people working on providing functionality similar to what Hopac provides under fsprojects.  Perhaps you can replace ActionBlock with async, MailboxProcessor, AsyncSeq or something like that.

**Comment by seemantr** [comment]
@VesaKarvonen Thanks for the reply. I will definitely checkout the book. Actually one thing I really like about Hopac is that it provides a consistent way to deal with Tasks, asyncs and observable.
