### ISSUE TITLE
How does Alt work inside?

### ISSUE THREAD

**Issue by slav** [Hopac/Hopac#62]
From my understanding Alt is used specifically to sync Jobs, especially when there're several potential sources. They allow me to, depending on which Alt becomes available, run continuation on that Alt. Did I get it right so far?

Alt.guard allows me to run a job that would create an Alt on which caller would be able to "wait" on. So it's almost as a factory pattern?
Alt.withNackJob is where things get confusing. It seems that it's almost an if..then..else type of branching.  Where code for "then" is executed if Alt becomes available, and "else" is executed if Alt is "cancelled"?

If I do `run (Alt.choose [verbose (Alt.never ()); verbose(Alt.always 2)]) ;;` from documentation I get
"Instantiated and Instantiated and committed to.
aborted."
This seems to show that Alt1 is created, then Alt2, then choose sees Alt2 is "available" and calls it, and afterwards cancels Alt1. Is this correct?

I'm not understanding who, in general would invoke nack. For example, looking at benchmark, FibNck. fibWithNack takes as an arg (cancel: Alt<int64>). It seems to then use cancel as an Alt, in other words if cancel becomes "flagged" it just returns.

below it fib is defined with as
```
    Alt.withNackJob <| fun nack ->
    Promise.start (fibWithNack n (nack >>%? 0L))
```
How does it work here? How does the client can use nack to indicate to the server that it's not interested in response anymore? Or am I misunderstanding purpose of nacks? What happens underneath? With choose, are all Alts that didn't get available first just abandoned?

I'm sorry if my questions seem trivial, but this style is very new to me, still learning.

**Comment by VesaKarvonen** [comment]
> From my understanding Alt is used specifically to sync Jobs, especially when there're several potential sources.  They allow me to, depending on which Alt becomes available, run continuation on that Alt.  Did I get it right so far?

Yes, it sounds like you did.

The Alt mechanism is a way to encapsulate client-server protocols as selective operations with one commit point.  By client-server it is simply meant that there are two concurrent entities where the client is the one that initiates the communication.  By protocol it is meant that there is some sequence of messages (one or more) being passed between the client and the server.  By having one commit point it is meant that protocols that you can encapsulate with the alt mechanism must have at most one point, a primitive message passing operation (client succesfully sends/receives a message to/from the server or vice versa) that is succesfully completed, where it is decided whether the operation is to be carried to completion or rolled back as if it never happened.  By selective it is meant that you can then combine such encapsulated protocols using `choose` to non-deterministically perform at most one such operation.

> Alt.guard allows me to run a job that would create an Alt on which caller would be able to "wait" on.  So it's almost as a factory pattern?

Hmm... What do you mean by a factory pattern?  Something from GoF?

I wouldn't call it a factory pattern.  `guard` is simply a way to attach pre synchronization actions to an alternative or to simply create an alternative that has pre synchronization actions.  Consider the following snippet

```fsharp
let anAlt = Alt.guard << Job.delay <| fun () ->
  let replyIVar = IVar ()
  server <-+ Request replyIVar >>%
  replyIVar
```

Above the code inside the guard is basically an action that will be executed each time the guard is being instantiated.  The action is executed before the alternative, namely the IVar being returned, is attempted to be synchronized on.

> Alt.withNackJob is where things get confusing.  It seems that it's almost an if..then..else type of branching.  Where code for "then" is executed if Alt becomes available, and "else" is executed if Alt is "cancelled"?

Roughly yes.  The idea is that the negative acknowledgment can be used by the server side of a communication to know whether a client is still waiting for the reply or not.  Consider the [example](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Alt.withNackJob) from the documentation of withNack.  The server side is a concurrent job that waits for requests from clients on the `reqCh` channel.  Each request must include a `nack` and a `replyCh` channel.  When the server tries to reply to a client, it tries to either synchronously give the reply to the client on the `replyCh` of the client or to acknowledge the `nack`.  The client side operation uses `withNackJob` to create a request, including a fresh reply channel, and passes the channel and the nack to the server as parts of the request.  If the client side operation is combined with other operations using `choose` (or e.g. `<|>?`) and it happens that some other operation is committed to then the `nack` becomes enabled and the server side acknowledges it and cancels the operation.

> If I do run (Alt.choose [verbose (Alt.never ()); verbose(Alt.always 2)]) ;; from documentation I get "Instantiated and Instantiated and committed to.  aborted."

> This seems to show that Alt1 is created, then Alt2, then choose sees Alt2 is "available" and calls it, and afterwards cancels Alt1. Is this correct?

Roughly yes.

> I'm not understanding who, in general would invoke nack.  For example, looking at benchmark, FibNck.  fibWithNack takes as an arg (cancel: Alt).  It seems to then use cancel as an Alt, in other words if cancel becomes "flagged" it just returns.

Sorry, the banchmarks are just that, benchmarks, that are used to measure the costs of specific operatins.  The fib nack isn't a particularly good example of using withNack.  Better examples of withNack would be:

* FrequencyServer: [fsi](https://github.com/Hopac/Hopac/blob/master/Examples/Misc/FrequencyServer.fsi) and [fs](https://github.com/Hopac/Hopac/blob/master/Examples/Misc/FrequencyServer.fs)
* LockServer: [fsi](https://github.com/Hopac/Hopac/blob/master/Examples/Misc/LockServer.fsi) and [fs](https://github.com/Hopac/Hopac/blob/master/Examples/Misc/LockServer.fs)
* SelectableQueue: [fsi](https://github.com/Hopac/Hopac/blob/master/Libs/Hopac.Extra/SelectableQueue.fsi) and [fs](https://github.com/Hopac/Hopac/blob/master/Libs/Hopac.Extra/SelectableQueue.fs)

The FrequencyServer example is adapted from the Erlang Programming book by Cesarini and Thompson.  The LockServer example is from the Concurrent Programming in ML book by John Reppy.  The SelectableQueue example is from the paper [Kill-Safe Synchronization Abstractions](https://www.cs.utah.edu/plt/publications/pldi04-ff.pdf) by Matthew Flatt and Robert Bruce Findler.


> below it fib is defined with as

```fsharp
Alt.withNackJob <| fun nack ->
Promise.start (fibWithNack n (nack >>%? 0L))
```

> How does it work here?  How does the client can use nack to indicate to the server that it's not interested in response anymore?

By simply using `choose`, for example, you could write

```fsharp
choose [fib 10L; fib 20L; fib 5L]
```

This would mean that three fib computations would be started in parallel.  The result of the `choose` would be the result of the fib computation that produces the result first.  The other computations would be given a negative acknowledgement and they can then stop their computations.

> With choose, are all Alts that didn't get available first just abandoned?

The client that uses `choose` abandons all the alts except the one that was chosen.  However, alts that used `withNack` get the negative acknowledgment.

Note that there is no magic involved.  A programmer using the alt mechanims must program alternatives in such a way that they make sense to use with `choose`. The various combinators and mechanisms make that possible.  See the [rules of thumb](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Alt) in the documentation of alt to get a rough understanding of how alternatives can encapsulate protocols with various properties.

> I'm sorry if my questions seem trivial, but this style is very new to me, still learning.

Feel free to ask questions, but I highly recommend reading the Concurrent Programming in ML book by John Reppy.
