### ISSUE TITLE
Re-enable Travis-CI?

### ISSUE THREAD

**Issue by haf** [Hopac/Hopac#68]
You could re-enable [Travis CI](https://travis-ci.org/Hopac/Hopac). There are up-to-date packages for [linux](http://www.mono-project.com/docs/getting-started/install/linux/) available, too, so you don't have to keep the osx build config. Place badge in README.

**Comment by VesaKarvonen** [comment]
Would you like to have commit access to the repo so you could just make it happen?

**Comment by haf** [comment]
Sure, I'll fix. But in that case I'm going to stay around the edges fixing stuff like this until I know more about the code.

**Comment by VesaKarvonen** [comment]
There is no requirement to work on anything particular.  If you see something that makes things easier for you and shouldn't cause problems for others, then feel free to make changes.  For bigger changes I recommend opening an issue/pull request to discuss first.

**Comment by haf** [comment]
Yes, agreed.

**Comment by haf** [comment]
Travis is taking some time to recognise the new org... I'll put together a best-bet at .travis in the meanwhile.

**Comment by haf** [comment]
First cut at a fix: fca663ae23f131c0c7aa9e7c74ff77444bffde19 - I also e-mailed the Travis people to ask about how long it normally takes.

**Comment by VesaKarvonen** [comment]
I wonder if pressing the Sync button on Travis might have helped?

**Comment by haf** [comment]
I tried that but that didn't work. Perhaps if you press it though it will see the new user in the org ;) 
![screen shot 2015-05-23 at 14 24 07](https://cloud.githubusercontent.com/assets/193115/7784025/6b334154-0157-11e5-9714-0a555bfc4692.png)

**Comment by VesaKarvonen** [comment]
That is what I tried, so apparently it doesn't sync org changes.

**Comment by haf** [comment]
In a related note: I've set myself a deadline in learning your API ;) http://www.meetup.com/FuncProgSTHLM/events/222707463/

**Comment by VesaKarvonen** [comment]
Cool.  Feel free to ask questions as usual and thanks for looking into Travis-CI!

**Comment by haf** [comment]
Re-enabled, currently building.
