### ISSUE TITLE
Throwing an error inside an Promise hangs silently

### ISSUE THREAD

**Issue by mavnn** [Hopac/Hopac#73]
``` fsharp
let promise2 : Promise<unit> =
    Job.raises (Exception "Boo")
    |> Promise.Now.delay

promise2 |> Job.Global.run
```

hangs indefinitely rather than throwing. Is this expected behaviour?

**Comment by VesaKarvonen** [comment]
No that is not expected behavior, but I believe this was reported as #72 and fixed yesterday.  Are you using the latest version?

**Comment by mavnn** [comment]
oops! Just noticed #72. As you were...
