### ISSUE TITLE
Job Try Finally not catching exceptions

### ISSUE THREAD

**Issue by mavnn** [Hopac/Hopac#74]
I could be doing something wrong somewhere, but this test fails for me (the exception is not caught):

    [<Test>]
    let ``Job try finally works`` () =
        let finallyFired = ref false
        let act = job {
            try
                failwith "I will always fail!"   
            finally
                finallyFired := true            
        }
        act |> Job.Global.run |> ignore
        Assert.True(!finallyFired)

The same test for ``try ... with`` works fine. I'm afraid I don't yet understand enough of how the Job.tryFinally methods are implemented to have a good idea for a fix.

**Comment by VesaKarvonen** [comment]
Quick reply: The assertion is never executed, because `Job.Global.Run` raises the exception; `finally` lets exceptions propagate outwards.

**Comment by mavnn** [comment]
... doh. Now I feel stupid!

**Comment by mavnn** [comment]
Annnd found the bug in my own code that prompted me to write the test. Thanks (and sorry) @VesaKarvonen

**Comment by VesaKarvonen** [comment]
No problem!  Glad that you found the bug.
