### ISSUE TITLE
Why is nack a Promise<unit> and not Alt<unit>?

### ISSUE THREAD

**Issue by slav** [Hopac/Hopac#75]
I'm just curious about why nack is a promise? In all examples it's used as an alt.

**Comment by VesaKarvonen** [comment]
Nack used to be just an `Alt<unit>`.  The semantics of nack is at most once, which means that it is compatible with `Promise<unit>`.  The reason it was changed to a `Promise<unit>` is that it allows the status of the nack to be [polled](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Promise.Now.isFulfilled) quickly.  This allows, for example, a nack to be used a kind of cancellation token like thing and to write a [cancellable job builder](https://github.com/Hopac/Hopac/issues/33#issuecomment-67754873) (the sketch uses `IVar<unit>`, but `Promise<unit>` is more general).  You could then write a server that, upon receiving a client request, performs work in a separate cancellable job, where the cancellation is implicit via the nack of the alternative mechanism.
