### ISSUE TITLE
Adding `^` similar to `$` in Haskell?

### ISSUE THREAD

**Issue by polytypic** [Hopac/Hopac#82]
See the unlispify branch.  Adding `^` similar to `$` in Haskell basically allows one to remove more parentheses and to rely more on layout.  In particular, it allows one to remove parentheses from the user defined funs in a pipeline expression. For example,

```fsharp
xs
|> List.filter (fun x ->
   x <> 0)
|> List.map (fun x ->
   x + 1)
```

can be written as

```fsharp
xs
|> List.filter ^ fun x ->
     x <> 0
|> List.map ^ fun x ->
     x + 1
```

Also, it allows one write nested function applications such as

```fsharp
f << g <| h x
```

more concisely as

```fsharp
f ^ g ^ h x
```

F# already defines the `^` operator as string concatenation, for ML compatibility, but also gives a diagnostic suggesting that you should use `+` rather than `^`.

What do you think?

**Comment by vasily-kirichenko** [comment]
it is hard to say immediately if real world code will become more readable with this operator. I will define it outside Hopac and try to use, then give feedback.

**Comment by polytypic** [comment]
There are some more examples [here](https://github.com/polytypic/Infers/commit/612e09c8acad7d9ff90fb321b680a1d2b7cf37e3) (scroll down for some meatier examples).  The `^` operator isn't really specific to Hopac in any way. Ideally the `^` operator would come from F# core libraries.

Personally I find that I dislike having to mix both indentation and parentheses for grouping in F#.  The diffs between using parentheses and using `^` aren't necessarily dramatic when you just look at a finished snippet of code.  The difference is more pronounced when you are actually editing the code and moving (potentially large) blocks of code around.  When one mixes both parentheses and indentation, it is not uncommon to end up with code whose indentation is correct, but one or more parentheses are in the wrong place and then one tends to get rather unhelpful error messages.

**Comment by vasily-kirichenko** [comment]
I see, thanks. I like it. What about
```fsharp 
static member UInt8 = O ^ prim (fun r -> r.ReadByte ()) (fun w -> w.Write)
````
? 

Why is it not possible to replace all the parenthesis with `^`?

**Comment by polytypic** [comment]
In the example case, to eliminate all parens, one could write:

```fsharp
static member UInt8 =
  prim <| fun r -> r.ReadByte ()
       <| fun w -> w.Write
  |> O
```

But turning a one-liner into multiple lines just to eliminate parentheses seems like a poor trade-off.

But, in general, none of the existing `|>`, `>>`, `<<` and `<|` alone or the "new" `^` alone or even all of them together works in all cases (especially if you consider expressions involving other operators).

**Comment by polytypic** [comment]
Another [example](https://github.com/Hopac/Hopac/commit/fd6a945a477eb1a76adcc7e384aeb80c14750211).

**Comment by vasily-kirichenko** [comment]
Yes, stuff like

```fsharp
|> Stream.merge ^ filterOn main.FilterAll isAny
|> Stream.merge ^ filterOn main.FilterActive isActive
|> Stream.merge ^ filterOn main.FilterCompleted isCompleted
```
looks unusual but cleaner.

**Comment by polytypic** [comment]
Thanks for the feedback!  I'll close this issue and delete the branch.  I will likely be using the operator internally.

**Comment by slav** [comment]
I know this is closed, but perhaps using ^<| instead of just ^ would make it easier to comprehend the purpose of the operator?

http://tryfs.net/snippets/snippet-4o
