### ISSUE TITLE
Hopac memory footprint

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#83]
Where could Hopac be placed in this list? :)

![image](https://cloud.githubusercontent.com/assets/873919/11434668/1fd508a0-94e1-11e5-98f4-67e0e2fc1524.png)

**Comment by polytypic** [comment]
Well, absolutely minimal memory usage is under 100 bytes (at least for 32-bit).  A bit more realistic examples are a few hundred bytes.  Several of the benchmarks (e.g. Cell and ThreadRing) print out memory usage information (and are compiled to prefer 32-bit, so on a 64-bit machine you should see 64-bit results).  Note that getting accurate memory usage information from GC is not easy, so the numbers can sometimes be completely bogus.
