### ISSUE TITLE
F# Core 4.0

### ISSUE THREAD

**Issue by haf** [Hopac/Hopac#86]
Hi,

I think you should leave the F# core library at 3.1.2.5 unless there's a really good reason. The fact that you've upgraded means I can't use Hopac in any library.

**Comment by dsyme** [comment]
The recommendation on fsharp github.io is that libraries should target the earliest and most portable FSharp.Core possible, eg 4.3.1.0 (nuget 3.1.2.5) or a PCL (eg profile 47, also in nuget 3.1.2.5) to maximize the number of users who can benefit from the library.

**Comment by neoeinstein** [comment]
Posted a PR that would revert back to 3.1.2.5. I agree on the reference version as well as I too would like to reference Hopac from a library.

**Comment by neoeinstein** [comment]
While we are in the neighborhood here, would it make sense to also set up Hopac and Hopac.Core as portable libraries? I'm happy to try, though there may be an issue with re-targeting Hopac.Core to a PCL (not sure what it depends on from the BCL). Benefit from getting onto PCL is that it will open the library up to use from .NET Core and .NET Native when F# support is ready in 2016.

**Comment by haf** [comment]
As long as it works with mono. I think I was the one convincing Vesa to make it a normal library, because using it as a portable library was fairly painful.

**Comment by dsyme** [comment]
I encourage switching F# libraries to Profile 78 or 259 where possible for the reasons mentioned above, or adding these as an extra configuration in the nuget package. Consuming these on mono should be possible. If there's any pain we'll have to fix that.

**Comment by haf** [comment]
As long as they show up in Xamarin Studio/MonoDevelop. That has been the issue previously, making development using any library touching them, impossible.

**Comment by polytypic** [comment]
I reverted the FSharp.Core dependency.  Regarding PCL, the library has been basically factored to make that possible, but when I tried to use PCL profiles, I couldn't get things to work smoothly.  If someone knows enough about PCL (I haven't seen a really good document about it) to make things work, then I'm all for it.

**Comment by neoeinstein** [comment]
I'll take a swing at it, and see what I can come up with.

**Comment by dsyme** [comment]
I made some notes on adding PCL builds of functionality to existing F# library packages targeting .NET 4.x  https://github.com/fsprojects/FsProjectsAdmin/issues/10#issuecomment-164817788.  I hope they are useful.

**Comment by 7sharp9** [comment]
@haf / @neoeinstein Was this resolved?

**Comment by haf** [comment]
@7sharp9 the revert that this issue was about; yes. The profiles suggested, no, unfortunately.
