### ISSUE TITLE
When can we call run without deadlocking?

### ISSUE THREAD

**Issue by haf** [Hopac/Hopac#87]
Greetings,

We've done a rather large rewrite towards Hopac, and are running into some problems around async+job interop, with the older version of Logary (stable). LogManager.GetLogger does a:

``` fsharp
let getLogger name =
  actor |> postWithChan (fun respCh -> GetLogger (name, respCh)) |> Async.RunSynchronously
```

Which leads to the full system locking up in a series of Monitor.WaitOne calls, all Hopac threads blocked. Adding an internal System.Console target somehow unlocks the system, perhaps because System.Console itself takes a lock when writing or perhaps because it changes the ordering of things.

The reason I want RunSynchronously is that I'm initialising loggers that are private static on a module level. It may very well be that the static modules are initialised before loggers are available, but that shouldn't make a difference since we have a flyweight that replaces all instances with configured ones when Logary is started.

So my question is whether you've run into something like this before, or have any pointers for us?

It also leads to really strange Async behaviour with Suave:

```
listener started in 16292.745 ms with binding 127.0.0.1:8081 [Suave.Tcp.tcpIpServer]
```

**Comment by polytypic** [comment]
Where/How is `postWithChan` defined?

**Comment by polytypic** [comment]
I can't find the definition of `postWithChan` by grepping the Logary `*.fs` sources (master and feature/hopac branches) so it is difficult to analyze the issue in detail.  Is it using `run` internally?  It should not be necessary in this case, because you can convert a `Job<'x>` to an `Async<'x>` using e.g. [ofJob](http://hopac.github.io/Hopac/Hopac.html#def:val Hopac.Extensions.Async.Global.ofJob).  That way you can run jobs without having _Hopac code_ take any long term locks.  See also this [issue](https://github.com/Hopac/Hopac/issues/21).

**Comment by haf** [comment]
Hi there,

Sorry about the late reply; here's the code;

 - https://github.com/logary/logary/blob/master/src/Logary/Registry.fs#L17
 - https://github.com/logary/logary/blob/master/src/Logary/Registry.fs#L26
 - https://github.com/logary/logary/blob/master/src/Logary/Registry.fs#L46
 - https://github.com/logary/FSharp.Actor-logary/blob/feature/req-repl/src/FSharp.Actor/Actor.fs#L246-L259

And this is called from code like:

module Mod =
  let private logger = Logging.getLoggerByName "logibit.ReadModel"

Which calls `Registry.GetLogger(:string) : Logger`

**Comment by polytypic** [comment]
What does `Idempotence.initialize` do?  Is it synchronously waiting for the result of something asynchronous?

**Comment by haf** [comment]
I don't think so:

```
  [<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
  module IdempotentEvent =

    let initialise mgr =
      let exec a = Sql.execNonQuery mgr a [] |> ignore
      exec "
CREATE TABLE IF NOT EXISTS seen_events
  ( event_id TEXT
      CONSTRAINT ix_event_id
      UNIQUE
      ON CONFLICT ABORT,
    first_seen TEXT
      NOT NULL )"

  let initialise mgr : Async<_> =
    IdempotentEvent.initialise mgr
    async.Return ()
```

**Comment by polytypic** [comment]
Not that this would necessarily be the cause, but here is a troublesome pattern:

```fsharp
    interface FlyweightLogger with
      member x.Configured lm =
        lock locker (fun () ->
          logManager := Some lm
          logger := Some (Async.RunSynchronously(getLogger lm.registry name)))
```

One should avoid taking locks for the duration of potentially long running operations.  Looking at the code it would seem that you could change it to:

```fsharp
    interface FlyweightLogger with
      member x.Configured lm =
        let logger' = Async.RunSynchronously <| getLogger lm.registry name
        lock locker <| fun () ->
          logManager := Some lm
          logger := Some logger'
```

Better yet would be to expose the operation as an `Async`.

**Comment by polytypic** [comment]
Actually the whole lock expression seems unnecessary.

**Comment by mausch** [comment]
I can confirm that `Sql.execNonQuery` is not async, at least not until it calls ADO.NET which is the scope of FsSql. It might be that the ADO.NET driver you're using is async behind the curtain, but this seems unlikely. If you wanted to test that, you could try running the code against a different db engine.

**Comment by haf** [comment]
@mausch @polytypic Thanks to you both for your answers.

In the v4 process I've made them both async, so hopefully we can live long enough with the 'print to console a bit' hack, till v4 is released proper. Still wondering about doing a 'run' to initialise static fields, though?
