### ISSUE TITLE
Elaborate on Erlang style selective communication vs CML style selective communication

### ISSUE THREAD

**Issue by VesaKarvonen** [Hopac/Hopac#9]
Hypothesis: Erlang style pattern matching based selective communication (which also obviously works with CML) is good for implementing internal/closed protocols while CML style selective communication is good for external/open combination of such protocols.  Write documentation to elaborate on this hypothesis.  Show how issues, such as need to filter mailbox contents and race conditions that seem to be frequent in the Erlang Programming book, are due to attempts to do external combinations of otherwise perfectly working internal protocols and how CML style events help to avoid such problems with ease.

**Comment by eulerfx** [comment]
Some related discussion here: https://github.com/reactivemanifesto/reactivemanifesto/pull/34

**Comment by VesaKarvonen** [comment]
@eulerfx Interesting conversation ( reactivemanifesto/reactivemanifesto#34 ).  Thanks for the heads up!

I think all the most important points were already said there.  The idea of synchronous message passing seems to be easily mistaken for something like synchronous RPC.  That is a shame.  CML, Racket and Hopac are not that well known.  Go and Clojure core.async and pi-calculus are perhaps better recognized and I don't see a lot of people arguing that those would not be suitable for "reactive" programming.  As you know, CML/Racket/Hopac is basically an additional abstraction layer on top of pi-calculus with non-deterministic choice.  A bit like "Go++" or "core.async++".

Of course, it is right that asynchronous message passing is a better model for distribution.  However, for concurrent abstractions on a single machine, possibly with shared memory, when message delivery is guaranteed, synchronous message passing can offer advantages, like you say.

Note that there is no technical reason why Hopac should be limited to CML style abstractions.  In fact, Hopac already provides many primitives that are not included in the original core CML implementation.  If I have use for them, I will surely add "remote mailboxes" (see #10) and other abstraction for distributed programming into Hopac.  It might even make sense to implement join-calculus style pattern matching for such mailboxes (see #37).
