### ISSUE TITLE
nack inside caller

### ISSUE THREAD

**Issue by haf** [Hopac/Hopac#90]
How would I make something like this compile?

``` fsharp
module internal Job =
  let apply fJob xJob =
    fJob <*> xJob >>- fun (fN, x) -> fN x
module internal List =
  open Hopac.Infixes
  
  /// Map a Job producing function over a list to get a new Job using
  /// applicative style (parallel). ('a -> Job<'b>) -> 'a list -> Job<'b list>
  let rec traverseJobA (f : 'a -> Job<'b>) (list : 'a list) : Job<'b list> =
    let cons head tail = head :: tail
    let initState = Job.result []
    let folder head tail =
      Job.apply (Job.apply (Job.result cons) (f head)) tail
    List.foldBack folder list initState

  let send targets msg : Alt<_> =
    Alt.withNackJob <| fun nack ->
    targets |> List.traverseJobA (fun target ->
      upcast ((Log msg |> Ch.give target.reqCh) <|> nack))
```

I want the client to choose when to abort using the selective Alt returned from `send`, but the server should always complete.

**Comment by haf** [comment]
Another formulation that seems to work;

``` fsharp
  let send targets msg : Alt<_> =
    Alt.withNackJob <| fun nack ->
      let res : Alt<_> =
        (targets |> List.traverseAltA (fun target ->
          let ack = IVar ()
          Alt.choose [
            target.reqCh *<- Log (msg, ack)
            nack :> Alt<_>
          ]))
        ^->. ()
      Job.result res
```

**Comment by haf** [comment]
In short I'm having trouble making this test pass:

``` fsharp
    yield testCase "after shutting down no logging happens" <| fun _ ->
      printfn "next"
      Fac.withLogary <| fun logary out err ->
        let logger = (pnp "a.b.c.d") |> Registry.getLogger logary.registry |> run
        (because "logging something, then shutting down" <| fun () ->
          "hi there" |> Logger.info logger |> run
          logary |> Config.shutdownSimple |> run |> ignore
          printfn "unit test back in control"
          let didLog =
            Alt.choose [
              timeOut (TimeSpan.FromMilliseconds 20.0) ^->. false
              ("after shutdown" |> Logger.info logger) ^->. true
            ] |> run
          Assert.Equal("should be false", false, didLog)
          logary |> finaliseLogary
          out.ToString())
        |> should contain "hi there"
        |> shouldNot contain "after shutdown"
        |> thatsIt
```

**Comment by haf** [comment]
The code is here: https://github.com/paavohuhtala/logary/pull/4/files

And the trace from the printfn:

```
textwriter awaiting
sending msg
send job called
nack full? false
textwriter got msg Log
  ({name = PointName ["a"; "b"; "c"; "d"];
    value = Event "hi there";
    fields = map [];
    session = Object (map []);
    context = map [];
    level = Info;
    timestamp = 1450116887006637000L;},Hopac.IVar`1[Microsoft.FSharp.Core.Unit])
textwriter awaiting
ack Log
alt map
alt map
textwriter got msg Flush (Hopac.Ch`1[Microsoft.FSharp.Core.Unit],Hopac.Core.Nack)
textwriter awaiting
textwriter got msg Shutdown (Hopac.Ch`1[Microsoft.FSharp.Core.Unit],Hopac.Core.Nack)
textwriter: disposing
textwriter: acking
textwriter: zero
unit test back in control
sending msg
send job called
nack full? false
```

**Comment by polytypic** [comment]
Quick comment regarding `traverseJobA`: although not strictly optimal for parallel programming, [Seq.Con.mapJob](http://hopac.github.io/Hopac/Hopac.html#def:val Hopac.Extensions.Seq.Con.mapJob) is likely to be much faster.

**Comment by haf** [comment]
Ah, I see. Thanks. I didn't have need for it though – it's currently unused; because I need nack to come along the invocations so the results of the calls can be ignored.

**Comment by polytypic** [comment]
Have you studied the toy example in the documentation of [withNackJob](http://hopac.github.io/Hopac/Hopac.html#def:val Hopac.Alt.withNackJob)?

The "client side operation" is usually defined using withNack and the nack is sent to the server along with a reply channel.   The server then does what it needs to do and can then use the nack to determine whether the client is still waiting for the reply.

**Comment by haf** [comment]
I've probably studied that particular set of paragraphs for more than an hour.

**Comment by polytypic** [comment]
Do you have a google account?  Invite me for a chat?

**Comment by polytypic** [comment]
If I understand correctly, you want to express a simple scenario where:

* A client initiates an asynchronous operation.

* The client can, but is not required to, wait for the completion of the asynchronous operation.

* Regardless of whether the client waits for the operation to finish or not, the operation is performed to completion.

If that is the case, then a promise should be sufficient.

**Comment by haf** [comment]
Chat invite sent =)

You're correct; a promise should do it. Can those also be spawned in parallel?

**Comment by haf** [comment]
I think I've settled on:

``` fsharp
/// Send the target a message, returning the same instance as was passed in when
/// the Message was acked.
let log (i : TargetInstance) (msg : Message) : Alt<Promise<unit>> =
  let ack = IVar ()
  (Log (msg, ack) |> BoundedMb.put i.requests)
  ^->. (ack :> Promise<unit>)
```

**Comment by polytypic** [comment]
Yes, that should support both backpressure and notification of completion.
