### ISSUE TITLE
This not work on mono?

### ISSUE THREAD

**Issue by mamcx** [Hopac/Hopac#91]
I wish to use CSP instead of actors ([event asking if is possible to layer CSP on top of it](https://stackoverflow.com/questions/35469691/how-implement-csp-on-top-of-agents-in-f/35483782#35483782)) and found your library, but it not install with nuget on OSX:

> Could not install package 'Hopac 0.1.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework.

Is this because exist a low-level block that will make it hard to run on other platforms (osx, linux, ios, etc) or is lack of users there?

**Comment by polytypic** [comment]
Hopac targets Mono / .NET framework version 4.5.

Xamarin, for example, picks 4.0 by default when you create a new project, but if you change that to 4.5 (Project Options -> Build -> General -> Target framework), you can install Hopac into the project.
