### ISSUE TITLE
Cannot build on windows

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#98]
1. build.cmd fails with:
```
> build.cmd
WARNING: An error occurred while loading packages from 'http://nuget.org/': The remote server returned an error: (404) Not Found.

WARNING: An error occurred while loading packages from 'http://nuget.org/': The remote server returned an error: (404) Not Found.

Unable to find package 'FAKE'.
WARNING: An error occurred while loading packages from 'http://nuget.org/': The remote server returned an error: (404) Not Found.

WARNING: An error occurred while loading packages from 'http://nuget.org/': The remote server returned an error: (404) Not Found.

Unable to find package 'SourceLink.Fake'.
The system cannot find the path specified.
```
2. VS suggested to restore packages and it succeeded with it. But it failed to build the solution:
```
1>------ Build started: Project: Hopac.Core, Configuration: Debug Any CPU ------
1>D:\github\Hopac\Libs\Hopac.Core\Assembly.cs(9,12,9,48): error CS1726: Friend assembly reference 'Hopac.Platform' is invalid. Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.
1>D:\github\Hopac\Libs\Hopac.Core\Assembly.cs(8,12,8,39): error CS1726: Friend assembly reference 'Hopac' is invalid. Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.
```
What's the story with strong naming? I don't need it at all, is it possible to build the solution and NuGet package without all this SN stuff?

**Comment by haf** [comment]
The story is that I am trying to use Hopac with a strongly named Windows application which unfortunately has the legacy of requiring all of its dependencies to be strongly named. I've filed a bug with the F# compiler:

https://github.com/Microsoft/visualfsharp/issues/1151

I'm doing to continue working on this Monday. It's also breaking @logary unfortunately... I'm not sure what is the actual error.

@vasily-kirichenko If you merge this https://github.com/Hopac/Hopac/pull/96 on Windows; does it work for you?

**Comment by vasily-kirichenko** [comment]
@haf yes, thanks it's built OK having that branch merged.

**Comment by polytypic** [comment]
@haf If I load the Hopac solution in either Xamarin on OS X or VS 2015 on Windows and rebuild all then the Streams benchmark and the AdHocTests test project fail to build.

**Comment by haf** [comment]
@polytypic Thank you, I'll fix this today.
